### ISSUE TITLE
Should maintainers merge significant PRs themselves?

### ISSUE THREAD

**Issue by jtigger** [exercism/discussions#115]
This is a question of social protocol in open source programming.  I'm very curious as to what folks think and more importantly the thought process behind it.

My question is:

In a repository where there are multiple active maintainers, under what conditions should a maintainer merge in their own PR?

**Comment by petertseng** [comment]
There are at least two protocols I've seen:

1. Once you've received approval from another maintainer, you are expected to merge your own PR at any time convenient to you.
    * This could make sense in very large projects where the reviewer might not know as much about the safety of the PR as the author, I suppose?
    * It seems like the approval says something like "this at least looks sane, but I'm assuming you know some intricate details about it that I do not, so you have to merge this at a time when you can take responsibility for it at release time!"
    * Sometimes it happens that the approver says "this looks good except for (very minor fix), just merge it after you apply that minor fix, you don't need me to look at it again"
2. It is expected that another maintainer will merge your PR.
    * This could reduce back-and-forth, so PRs will tend to get merged faster.
    * Another interesting effect of this protocol is that at least two people involved in this PR will show up in git history.
        * The author for the original commits, and then the merge commit.
        * Or, if the Squash and Merge was used, author + committer for the squashed commit.
        * Notice that in the merge-your-own protocol, the approver is usually not shown in git history - you must go to Github history.

I think when the Go track was mostly me and Katrina, we mostly used merge-each-other's.
Why did I personally do that? Because Katrina did!

I think most Exercism tracks I'm currently on do merge-your-own.
I don't know if there is a particular reason for it.
(Is it because people on those tracks started following *my* example? No idea, would have to ask them...)

I don't think any track I'm on has actually written down what the protocol is.
On another non-Exercism project I work on, it *is* written down that the protocol is merge-your-own, I think for reasons like what I wrote.
Perhaps I just carry on those habits.

**Comment by jtigger** [comment]
I was reading over the [guide for maintainers](https://github.com/exercism/exercism.io/blob/master/docs/maintaining-a-track.md#collaborate) for another reason and came across this passage:

> ... As a general rule, don't merge your own pull requests, unless they are utterly trivial. ...

This sentence is under the "collaborate" header; meaning that this wasn't just a stylistic suggestion, but motivated by the idea that we're doing this as a group.  @kytrinyx, am I interpreting that accurately?

**Comment by Insti** [comment]
Can we make a distinction between merging your own pull request, and merging your own pull request after it has been reviewed/approved by someone else?

**Comment by jtigger** [comment]
I'd take it one further, @Insti... seems to me that the review/approval is the actual important bit.  Who clicks the "merge" button is insignificant in comparison.

**Comment by kytrinyx** [comment]
> Can we make a distinction between merging your own pull request, and merging your own pull request after it has been reviewed/approved by someone else?

Yeah, agreed. I think that each track could decide what the protocol is, and that the important bit is that it gets reviewed and/or approved.

**Comment by jtigger** [comment]
As the guy who asked the question, I consider it answered.  Thanks for the discussion!  I made the pedantic edit in the referenced guide in exercism/exercism.io#3354.  Not sure if this question will ever be asked again, but I'll drop a "policy" tag on it just in case.

**Comment by petertseng** [comment]
My previous comment at https://github.com/exercism/discussions/issues/115#issuecomment-273544776 did not make clear what protocol I think I should use when working with this organisation; it was just some observations on the past and other organisations.

This is just FYI since I review and/or merge a nonzero number of PRs in problem-specifications and other repos. There is no need to make what I do an organisation-wide policy since what I do is probably compatible with a wide variety of others.

If I know for a fact that the author of the PR can merge it, I will almost never merge it. If I Approve it (in the GitHub sense) I encourage the author to merge it at a time convenient to the author!

If I submit a PR that I have not marked "Do not merge" I will always leave it in a mergeable state so that it can be merged by others if necessary. If I am able to merge it I will probably do so if I judge that I have received sufficient approvals. I promise that I will never judge zero approvals to be sufficient for me to merge my own PRs.
