### ISSUE TITLE
Procedure to propose a rename an exercise? 

### ISSUE THREAD

**Issue by masters3d** [exercism/discussions#12]
Is there a current way to suggest a change of name for an exercise ?

For example:
https://github.com/exercism/x-common/blob/master/perfect-numbers.md
should probably be called `number-classifier` because perfect is one of the classifications. 
It doesn't make sense to call a solution perfect number because that is not the only output. 

https://github.com/exercism/x-common/blob/master/robot-name.md
I don't like that the name of this exercise contains the word _name_. Why not just `robot`? 
Or `robot-manager`? 

Edit: specific names:

**Comment by kotp** [comment]
I noticed that the [wiki](exercism/x-common/wiki) is in place, and x-common is where the change would be affected.  Perhaps a process for name changes could be documented there?

It is actually nice to have the wiki there document the 'meta' things, as you can clone it in the project structure, ignore `wiki/` in your global excludes file for git and have it close at hand with or without network access, fully searchable, etc.

As to the suggested name changes, I don't think introducing case in the names makes sense, some file systems do not distinguish case for file names, and others do, so it introduces "another thing" to manage.  Of course, I am matching your supplied "NumberClassifier" to your explicit example of `master/perfect-numbers.md` so assuming you mean something like `master/NumberClassifier.md` as the change.

**Comment by masters3d** [comment]
I didn't mean to suggest a new format just the content. number-classifier works

**Comment by kytrinyx** [comment]
How about sticking the instructions in the [Contributing Guide](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md) once we come up with a procedure?

If the wiki is there, it's probably because I forgot to uncheck the box when I created the repo. I don't want yet another place to have to look--things are already so spread out as they are.

I agree that we shouldn't change the format; all-lowercase with hyphens is a format that works.

Name changes are kind of complicated at the moment, because the submission data depends on the problem slug. If we change the name then:

- old submissions should be renamed in the database so that they show up when you browse the exercise using the new name
- people who have submitted the exercise under the old name should not be given the exercise under the new name when they fetch
- people who submitted the exercise under the old name should be able to see and comment on the same exercise under the new name

There might be other things as well, which we would probably only discover the first time we do this.

**Comment by petertseng** [comment]
Anything we learned from deprecating point-mutations in favor of hamming that we could apply here?

**Comment by kytrinyx** [comment]
Yeah, that's what I was digging through my medium-term memory to attempt to retrieve. Those three points are what came to mind.

**Comment by IanWhitney** [comment]
@petertseng 

I saw one student in Rust who seemed confused by the name change. I figure they saw it in another track under the old name and wondered why Rust had a new name. It didn't cause any problems, just a question.

**Comment by kytrinyx** [comment]
See also: https://github.com/exercism/discussions/issues/12

**Comment by kytrinyx** [comment]
See also: See also: https://github.com/exercism/discussions/issues/40

**Comment by kytrinyx** [comment]
We have some dirty data here: https://github.com/exercism/xscheme/issues/44

**Comment by kytrinyx** [comment]
I've read through this issue a couple of times and I'm not sure whether this discussion is attempting to decide whether we should change the name of specific exercises, or decide what the process is in general.

It almost looks like it started as one and morphed into another.

So—in order to clarify things, I'm opening a new issue only to brainstorm how to safely perform a "rename exercise" procedure: https://github.com/exercism/discussions/issues/156

If you want to suggest that we rename specific exercises, @masters3d, please open an issue for each exercise so that we can discuss the problems with the name as well as possible alternatives.
