### ISSUE TITLE
Should we add docker images for individual language track repositories to make it easier to start contributing?

### ISSUE THREAD

**Issue by thelastinuit** [exercism/discussions#122]
Hey there guys,
A few days ago I asked @kytrinyx (twitter) if creating bundles (docker images with everything you need to start coding) would be a good idea? 
If I manage (or someone else) to create those docker images, i.e.: 
```bash
docker run --rm -it -v $(pwd):/code -w /code exercism/rust bash
```

And you can run your test or something else and not worrying about installation and stuff.
Perhaps it's not a big deal but well I'm scientist, I gotta doubt everything.

If this is not a great idea, please just close/remove this post.

Many thanks for all your hard work!

**Comment by rbasso** [comment]
I guess that it depends on how hard it is to set a development environment in the language versus the trouble to keep updated docker images.

I cannot speak for other tracks but, at least for the Haskell track, I don't think it is worthy, because installing *Stack* is probably easier and we don't have to manually install other dependencies.

**Comment by petertseng** [comment]
Oh interesting.

For the languages where I did not have permission to install on the development machine, I used Vagrant boxes to do it, but I didn't think there would be enough demand to share them.

For example here's mine for C++:

```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'ogarcia/archlinux-x64'
  config.vm.provision 'shell', inline: <<-SHELL
    ln -s /vagrant /home/vagrant/cpp
    pacman -Sy --noconfirm gcc cmake make boost
  SHELL
end
```

The maintenance problems are if the `config.vm.box` gets out of date (the upstream stops making updates and as a result the box does not function well for some reason), or the upstream distribution renames or removes packages.

**Comment by ErikSchierboom** [comment]
Interesting, I added this as a todo to the C# and F# track a couple of weeks ago (see https://github.com/exercism/xcsharp/issues/202). For some languages, I do think it would make sense. Running Docker images becomes more and more accepted, and for the C# and F# track, I can simply base the Docker images on the official .NET Core Docker images released by Microsoft.

It might be that not every language track is suitable, and certainly not everyone will use it, but I do think it is a good option to get people started. This could be incredibly useful in workshops or the like, where getting people to setup their computers takes away valuable time.

**Comment by mhelmetag** [comment]
I think this is a great idea. I see a few ways of doing this (two that I can think of):

1) We could create an exercism-cli base image (off of ubuntu or something) that would have the cli environment set up. Then each track could have an image based off that one with the individual language requirements.

2) Like @ErikSchierboom suggested, we could use the official language docker images and install the exercism-cli.

Seems great for workshops!

**Comment by rpottsoh** [comment]
How would this work for environments that require Windows?

**Comment by mhelmetag** [comment]
I would think that it would work fine because docker can work on Windows with no problems. But users would be on Linux based containers... so it would be different for people used to running things in a Window environment.

**Comment by ErikSchierboom** [comment]
For Windows environments, there are only Docker images for Windows Server and Windows Nano Server. However, they require a license for you to run them I believe. So if there is a track that depends on Windows, I think we're out of luck. But, even Microsoft's own C# and F# can now run on .NET Core, which is fully cross-platform.

**Comment by rpottsoh** [comment]
》For Windows environments, there are only Docker images for Windows Server and Windows Nano Server. However, they require a license for you to run them I believe. 

Thanks Erik, this is what I assumed and feared. 

Sent from my android device.

**Comment by kytrinyx** [comment]
I don't think this necessarily makes sense for all language tracks, but I think that it would be worth creating documentation about how to do it and when one might want to do it in the ["maintaining a track" directory in the docs repo](https://github.com/exercism/docs/tree/master/maintaining-a-track). A temporary measure would be to open an issue in the documentation repository summarizing what needs to be done, and including whatever useful information we currently have.

Then we should automatically generate an issue when [bootstrapping a new track](https://github.com/exercism/request-new-language-track) asking the new maintainers to consider whether it would be useful, pointing to the documentation. This is very simple to add by creating a markdown file in the root of the repository (e.g. https://github.com/exercism/request-new-language-track/blob/master/CONSISTENCY.md) and then referring to it in the bootstrap script (e.g. https://github.com/exercism/request-new-language-track/blob/master/bin/bootstrap#L40)

**Comment by kytrinyx** [comment]
@nilbus - is this related to what you're working on?

**Comment by nilbus** [comment]
Bootstrapping docker development environments is what I'm working on, yes. I'm introducing an exercism.io base image that will be built automatically on Docker Hub when exercism.io:master is updated. The local development Docker is built `FROM` that base image to drastically reduce initial setup and update build time.

This is helpful for the exercism.io app, because without it, the docker image can take 45-60 minutes to build. To the extent that we have time-consuming build times for these language track Dockerfiles, this same approach would also be useful.

My current take on the approach for each track would be:
1. Define a base image in a Dockerfile at the root of the repository that sets up the language-specific development environment, starting from an existing language image when feasible.
2. Create a Docker Hub automated build for the repository. Someone with write permissions to the repository must do this.
3. Facilitate local extension of the development environment by documenting how to create or by providing a `Dockerfile.dev` that starts `FROM exercism/<language>`, or by suggesting `docker commit`. This is the area where I'm currently working to figure out the best approach.

**Comment by jpreese** [comment]
We have an issue opened up in the C# repo to add support for docker. I recently started giving the issue more attention and was directed here, and it looks like we share a similar approach.

For your base image that all tracks would start from, were you thinking a Go image that installed the Exercism CLI?

I'd imagine every track would need exercism CLI, so in our case, we would take that image and install .NET Core on top of it.

**Comment by nilbus** [comment]
@jpreese
> base image that all tracks would start from

To clarify, I think it may work out better if most tracks actually don't share a common base image. Since go compiles static binaries so nicely (the release is a tarball containing only the 1 executable file), it's really easy to add the CLI to a docker image with any base. Nothing go-specific is required. Track images will require much less maintenance if they're based on track-language-specific base images (e.g. `microsoft/dotnet-framework`?).

The base image is intended solely to reduce build time. If a track image builds on top of an existing image maintained elsewhere and takes a trivial amount of time to build, then a base image is likely overkill.

Do you know of existing base images for C# that would be a helpful starting point? Beyond the Exercism CLI, what would you add on to create a good development image?

**Comment by ErikSchierboom** [comment]
@nilbus Oh yeah, Microsoft releases official Docker images for many platforms: https://hub.docker.com/r/microsoft/dotnet/

**Comment by jpreese** [comment]
@nilbus yeah that makes sense, installing the CLI is pretty trivial. 

The gain I was thinking about mostly was that I feel like everyone is going to install the CLI anyway. To do so, you'll need to grab a release from https://github.com/exercism/cli/releases/x.x.x in the Dockerfile.

So theres a ton of duplication up front with the Dockerfiles across the exercism tracks. Then on top of that, since you have to specify a release, tracks are going to have different versions of the CLI and if you want to update the CLI, you'll need to modify the Dockerfile. Whereas if everyone was based off of exercism-cli:latest, you'd never have to touch the Dockerfile.

But in favor of that, you lose the ability to be more granular if for some reason you want a different version of the CLI.

If this is the route we'd like to take, then I'm going to spin up a Dockerfile for the C# repo

Lastly, do we have an organization on Dockerhub? I'd like to submit the image to a more Exercism friendly repo than my own personal one.

**Comment by nilbus** [comment]
> So theres a ton of duplication up front with the Dockerfiles across the exercism tracks. Then on top of that, since you have to specify a release, tracks are going to have different versions of the CLI and if you want to update the CLI, you'll need to modify the Dockerfile. Whereas if everyone was based off of exercism-cli:latest, you'd never have to touch the Dockerfile.

Perhaps we could address this using Docker multi-stage builds. Consider this:
- An automated exercism/cli image build contains the CLI binary only, and stays up to date with the latest release or master.
- Each track has its own Dockerfile that follows this pattern:

```Dockerfile
FROM exercism/cli:2 as cli
FROM microsoft/dotnet:2-sdk
COPY --from=cli /usr/bin/exercism /usr/bin/exercism
…
```

Rather than using the `:latest` tag, we should at least use and specify tags indicating major or minor version number, so we don't get unexpected pre-release updates (e.g. nextercism CLI is 3.x).

> do we have an organization on Dockerhub?

Yes, we do. I believe Dockerhub permissions are set such that anyone with write permission on a GitHub repository can add automated builds for that GitHub repository to Dockerhub. Do you have write access to the C# repo?

**Comment by kytrinyx** [comment]
> nextercism CLI is 3.x

As long as it's in prerelease, it won't be marked as "latest". For what it's worth :)
And we won't be switching 3.x to "latest" until we move to the new site, at which point 2.x will no longer be viable.

**Comment by jpreese** [comment]
@nilbus That would work for me as well. My primary goal of everyone sharing the same base was that everyone had the same version of the CLI. I'm looking through the current images on dockerhub, and although they aren't necessarily "official", they all do the same wget cli x.x.x, most with different versions.

> Do you have write access to the C# repo?
I do! I haven't gotten to the point where I want to publish yet, but just wanted to get that discussion out of the way so I knew where to put it when I was done.

**Comment by iHiD** [comment]
> Should we add docker images for individual language track repositories to make it easier to start contributing?

I love this. I also love the idea that we give students the docker images to use to work through the tracks, not just make them for maintainers. You probably all have this in your minds already, but as it's not been explicitly said, I thought I'd add it. Can I propose changing the title to "learning and/or contributing"?

**Comment by kytrinyx** [comment]
the "latest" URL returns a 302 that contains a "Location" header that points to the most recent release:

```
$ curl -i "https://github.com/exercism/cli/releases/latest"
HTTP/1.1 302 Found
...
Location: https://github.com/exercism/cli/releases/tag/v2.4.1
```

Using that would mean that everyone would get the most recent version without having to update the docker image.

**Comment by jpreese** [comment]
Sounds good to me, I'm double thumbs up for the dedicated CLI image. There's a decent bit of ceremony involved in getting CLI into a docker image (download, unzip, move directories, clean up), and just keeps things a little neater and consistent.

**Comment by nilbus** [comment]
Having a CLI image built using the github _latest_ release, tagged in Dockerhub as `:latest` sounds like a good approach to me.

> @jpreese: My primary goal of everyone sharing the same base was that everyone had the same version of the CLI.

To reach this goal, in addition to updating the CLI docker image, we'll have to rebuild all the individual track images after each CLI release. Maybe this is something that we can include in our CLI release procedure.

**Comment by kytrinyx** [comment]
> Maybe this is something that we can include in our CLI release procedure.

If you all figure out exactly what needs to be done, would you submit a PR for discussion to https://github.com/exercism/cli/blob/master/RELEASE.md?

**Comment by kytrinyx** [comment]
I've been back and forth on the Docker question, and in general my conclusion is that Docker should only be added if the maintainers themselves feel comfortable maintaining the docker setup.

If not, I'd prefer it if community members create their own docker setup, and we can link to it as an "unofficial / community supported" setup from the CONTRIBUTING.md file.

I'm going to go ahead and close this issue, but if there's more to discuss, please open an issue in http://github.com/exercism/exercism.io/issues

**Comment by iHiD** [comment]
@nilbus Hello :) Is [this DockerHub account](https://hub.docker.com/u/exercism) one that you made? If so would you mind me taking control of it, and presuming that's ok, would you mind emailing me the details to jeremy@exercism.io please? Thanks! :)

**Comment by Stargator** [comment]
@iHiD Consider GitHub's CodeSpaces which will be releasing "soon", does that make the discussion concerning Docker moot?

**Comment by iHiD** [comment]
I don't know anything about them really. Could you expand on how they fix things etc pls? 🙂

**Comment by ErikSchierboom** [comment]
CodeSpaces will allow people to use a pre-built Docker image to code in. This means no longer having to install all the dependencies manually, just spinning up a Docker container and using that. I don't know exactly if one can build your own CodeSpaces and if you need special IDE support (you probably do), but the idea is perfect for us.

**Comment by iHiD** [comment]
Nice! 🙂
