### ISSUE TITLE
Shall we delete the exercism/todo repo?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#135]
For a long time we had a ton of not-actionable issues, and a workaround was to create the https://github.com/exercism/todo repo, which would let people find things to work on.

Now that we have mostly actionable issues (especially in the language tracks), and we're implementing probot/stale, I'd like to suggest that we delete the exercism/todo repository.

Thoughts? Am I forgetting something?

**Comment by petertseng** [comment]
Looked over the current open issues for any that aren't already represented by issues in other repos. Only one that looked like it might fit that bill is https://github.com/exercism/todo/issues/174.

Are there any useful discussions and historical context that we would lose if we deleted the repo? Any interesting issues that are linked-to by a lot of other issues (useful hub points to branch off and explore related issues)? I know it will be hard to comb the old issues to answer those questions; I'm sorry for suggesting this time-consuming work instead of providing answers.

**Comment by kytrinyx** [comment]
> Looked over the current open issues for any that aren't already represented by issues in other repos. 

Yeah, that was my impression as well.

I actually think that this has been mostly done. There's a bug in the exercism.io repo, but it's tracked.

> Are there any useful discussions and historical context that we would lose if we deleted the repo?

I think that even with 404s, the discussions and historical context is fine without it.

I'm going to delete it.
