### ISSUE TITLE
How shall we track active maintainers for each track?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#139]
A while back (#97) we did a bunch of work to figure out the current status of all the tracks—are they maintained? How many maintainers are currently active?

It would be great if we had a living document that kept track of this.

My suggestion would be to create a new key, `maintainers` in the `config.json` file for each track, and then we can generate the report dynamically using trackler (either on the site or elsewhere).

We could also have alumni in that document, for historical purposes.

Or we could have a different document, or different structure.

I would like to have this information tracked within the repository itself, however, not in a separate location.

@hilary @Insti @petertseng @ErikSchierboom y'all have been discussing this... thoughts?

**Comment by hilary** [comment]
I like the idea of a key in the config.json file for the track. It not only feels like good data design, it also sets us up to do some automated analysis / tracking at a mythical future point in time.

**Comment by petertseng** [comment]
As I understand it, the goal of this document will be to give us (who is "us"? Just organisation members? Or all potential contributors, even non-organisation members?) knowledge of the maintained-ness of each track, right? And this can be used to help contributors know whether their contributions will be responded to, or maybe encourage someone to ask to adopt a track?

Let me know if I got that right.

---

My below comment does not discuss exactly what form this living document will take, but about the rationale of having it:

I hope we expect for this document to provide significant benefits over using https://github.com/orgs/exercism/teams , since there are the immediately-seen disadvantages of **duplication of data** and this document being **not representative** at all of who actually has access to the respective repos.

The benefits I see:

* **Visible to the public**, not just organisation members. But if this is the only benefit we want and we accept it if the report is generated dynamically anyway, well, I imagine we also have the capability to generate the information from the Exercism teams. Indeed, I gave an API token the right scope and use it for https://gist.github.com/petertseng/460b93436817ee02f34a919216566966.
* **Fewer bottlenecks**, more community ownership: Only organisation owners can add members to the organisation, and only owners or team maintainers may change team membership. The document would be reviewable via the normal channels.
* **More representative** of who is *actively* maintaining: The counterpoint to the above point of the document being **not** representative of who actually could write, of course. Now, implication here is that the teams are not representative of the active maintainers. So the document is meant to solve that problem. If your position is instead that this problem should instead be solved by making the teams only contain the active members, that is an interesting issue and is currently discussed on the side in https://github.com/exercism/discussions/issues/102#issuecomment-299486850, but not here.

---

I note that the above point about community ownership implies that the answer to the inactivity question is that **the community decides**. The problem is not going away, since someone will still have to decide who is active enough to stay in the active maintainers section. It's just that each track may decide among itself, using its own standards, who its currently-active maintainers are. It's just like how [nodes declare each other faulty](https://www.usenix.org/system/files/login-logout_1305_mickens.pdf) in various distributed systems. If that is the ideal way of things, perhaps we may even reach a point where a change to the document causes a corresponding change to the https://github.com/orgs/exercism/teams ...!

**Comment by petertseng** [comment]
Right, the document. Whether that happens in individual repositories or in https://github.com/exercism/x-common/issues/780 I'm sure I'll be happy with whatever y'all pick.

Individual repositories:

* More focused reviewers, not all track maintainers want to hear about updates to the maintainer list of all other tracks.

https://github.com/exercism/x-common/issues/780:

* Don't need to dynamically generate, it's already all in one place.

**Comment by kytrinyx** [comment]
> More representative of who is actively maintaining

This is what I was thinking. This means that we don't necessarily take people's commit bit away when they are inactive, they can still be on the team, but they wouldn't be reflected in the list of currently active maintainers for the track.

If we keep it in the repo that you maintain, I think we're much more likely to be able to actually keep it fresh. And we can use trackler to trivially use the information on the exercism.io site.

**Comment by kytrinyx** [comment]
I'd like to be able to use this data to say "this is the state of the Exercism world today". Show people the active tracks, the ones who are at risk. The ones who need a significant hand in order to survive or thrive. I'm thinking that we can have tools that analyze the git history and run them every once in a while, to look at activity. Then we update the maintainers list for the repo based on that. I don't know what the thresholds would be for active/inactive, we've got a separate discussion going about that.

This isn't so much a duplication of source of truth, but a caching layer. We might decide to make the actual GitHub team reflect the active maintainership. If we do, we could use the GitHub API to get this data, but I don't necessarily want to make those requests every time. If the GitHub team doesn't reflect it, then we'd need to do git history analysis, which is complicated and expensive (it can be done with BigQuery and the GitHub Archive, but I'd rather not have to do it on a regular basis), so caching makes even more sense.

**Comment by tejasbubane** [comment]
I like the idea of putting the data in `config.json` and using trackler to keep show it on exercism. @Insti and I were discussing about this on gitter. The main idea was to have the current status of all tracks visible to public (especially new contributors). I wanted to have the data in sync with the changes so that it is upto-date, but we did not think of this approach and went with the maintainers file in xcommon. We should have opened an issue for discussion before diving into a conclusion, sorry about that.

This approach is far better IMO:

* More likely to remain upto-date when someone comes in or leaves since that track will be focused on updating itself.
* Less noise in `x-common` of all the updates letting it focus on exercises only.
* JSON data will be more structured than markdown and can be used at multiple places.

**Comment by ErikSchierboom** [comment]
> If we keep it in the repo that you maintain, I think we're much more likely to be able to actually keep it fresh. And we can use trackler to trivially use the information on the exercism.io site.
Absolutely.

I'm also in favor of keeping track of it in the track's repository.

**Comment by petertseng** [comment]
> We might decide to make the actual GitHub team reflect the active maintainership. If we do, we could use the GitHub API to get this data, but I don't necessarily want to make those requests every time.

Makes sense. Trackler already has the tracks together, so a solution where information is available in Trackler means no secret API token is necessary. Sometimes I wish https://github.com/orgs/exercism/teams could become public (so that no secret token is necessary), but I imagine that even if this were possible it would give the public an incomplete picture because of private organisation membership.

> I'm thinking that we can have tools that analyze the git history and run them every once in a while, to look at activity. Then we update the maintainers list for the repo based on that.

Oh interesting! I had thought the usual (or exclusive) means of updating it would be manual and by the maintainers of the respective tracks, but it would be interesting to see how tools can assist it. Who will run the tools and do the updates, if it is someone other than the track maintainers? (Basically, who is "we" in the above quote?)

> If we keep it in the repo that you maintain, I think we're much more likely to be able to actually keep it fresh. And we can use trackler to trivially use the information on the exercism.io site.

I can't predict for sure, but it seems that how the information is displayed will play a large role in how up-to-date people are incentivised to keep it (going off of the example of difficulties and topics in the exercises array). The currently envisioned uses seem good. If they fall out of date, I would think more along those lines.

**Comment by behrtam** [comment]
Subsidiarity makes sense to me but how will a track update it's maintainer status if there is no active maintainer left (many tracks only have 1 active). PR by someone else which has than to merged by @kytrinyx?

**Comment by kytrinyx** [comment]
> how will a track update it's maintainer status if there is no active maintainer left (many tracks only have 1 active).

That is an excellent question. I think this is where the suggestion of having a team of unmaintainers would help—people who have access to all tracks but are expected to only deal with the track if maintainers are not (or there are no maintainers).

**Comment by kytrinyx** [comment]
I think we've got this one solved with the `maintainers.json` file. I've got some automation in progress to use this to let track maintainers add new maintainers.
