### ISSUE TITLE
At what point should requested tracks be deleted if they don't get implemented?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#143]
We have several tracks that were requested, but have no implemented problems:

- [The Netwide Assembler][nasm] (requested on Sep 23, 2014)
- [Tcl][tcl] (requested on Aug 6, 2015)
- [TECO][teco] (requested on Mar 15, 2016 by @LegalizeAdulthood)
- [Smalltalk][smalltalk] (requested on Jan 22, 2017)
- [Chapel][chapel] (requested on Jan 25, 2017)
- [ClojureScript][clojurescript] ([requested on March 30, 2017](https://github.com/exercism/request-new-language-track/issues/15))

[nasm]: https://github.com/exercism/xnasm
[tcl]: https://github.com/exercism/xtcl
[teco]: https://github.com/exercism/xteco
[clojurescript]: https://github.com/exercism/xclojurescript
[smalltalk]: https://github.com/exercism/xsmalltalk
[chapel]: https://github.com/exercism/xchapel

**Comment by petertseng** [comment]
It seems clear why "immediately" is an unacceptable answer: then it would not be possible to make a new track (and we find new tracks desirable, right?)

It's not clear why "never" is an unacceptable answer. Please explain why! Is it because:

* It gives people a false hope that the track is upcoming?
* It looks ugly to have so many languages with the default icon?
* It wastes contributor resources when there are global initiatives like the exercises array, the exercises directory, TRACK_HINTS.md?
* They fall out of date with updates to https://github.com/exercism/request-new-language-track/blob/master/TRACK_README.md and the new-track issues?
* They contribute to Exercism being a "[sprawling 50 repository beast](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#we-will-gladly-help-you-help-us)"? (the number is woefully out of date) Making it hard for contributors to know where to go to contribute effectively?
* Other reason not listed here?

Since that is unclear, I have no choice but to give an arbitrary answer, and I pick [six months](https://github.com/exercism/exercism.io/blob/master/.github/stale.yml#L4) seems like an accepted period of time, right? Though could probably do with a few weeks' warning if there are maintainers signed up.

**Comment by kytrinyx** [comment]
> we find new tracks desirable, right?

I think so, yes.

> It's not clear why "never" is an unacceptable answer.

Of the ones you listed, I would agree with:

- false hope
- waste contributor resources when there are global initiatives
- they fall out of date (I've sometimes gone back and updated old tracks. See "waste contributor resources" above)

Additionally, it's yet another repository where contributors might be disappointed if we're not paying attention.

I think 6 months seems reasonable. Any number we choose is probably going to  be arbitrary.

> Though could probably do with a few weeks' warning if there are maintainers signed up.

Yes, I agree, that should certainly be part of the process.

**Comment by petertseng** [comment]
By the way, I like to look at https://github.com/exercism?language=shell from time to time since a track without exercises in its main language gets detected as Shell (fetch-configlet is a shell script). Ignore Bash, MIPS, and x-common obviously. Some tracks that didn't even make it on the website:

* https://github.com/exercism/xchapel
* https://github.com/exercism/xsmalltalk

**Comment by kytrinyx** [comment]
Ah, thanks. I'm adding those to the list at the top.

**Comment by kytrinyx** [comment]
I think they didn't make it on to the site because I didn't yet have my checklists worked out for adding new tracks. This process has been improved with the request-new-language-track repo.

**Comment by NobbZ** [comment]
I do think, 6 months is far too long.

Either we do have a `hello-world` available after a month, or it is obvious that the requestor doesn't have any further interest in getting the track added.

If we though see that he is struggling with getting travis up and running, we still can try to help and extend the deadline. But if there isn't any movement in the first month, I really don't think that a miracell will happen in the next 5 months.

**Comment by kytrinyx** [comment]
@NobbZ I think you're right that 6 months is too long. We would know if there was activity and they were stuck.

**Comment by Insti** [comment]
Could we change the point at which tracks become "exercism" tracks, by requiring more work to be done on them before they are made a part of the family?

* User forks a generic track-starter-pack repository.
* User takes however long they like to prepare the track.
* Exercism takes over the now working track somehow. (copy/fork/ownership reassignment/etc)

**Comment by NobbZ** [comment]
In general I like that idea @Insti and already thought about proposing it.

But then again, I had the fear, that there will be multiple people trying to kickstart "their" track and working on them without knowing of each other and will then request the integration more or less simultanously. We had to pick one or deny both until they managed to co-ordinate themselves.

Much work that had been done twice without any need.

But as I'm writing this, perhaps we can establish some kind of nursery, where new tracks will be created. Those nursery tracks wont show up on the webpage, but were able to get fetched through CLI, when one knows the track ID.

A track could then only be allowed to leave the nursery when all the technical points from the checklist are done, and considered "beta" and listed on the page.

A track in beta then stays in beta until we have enough maintainers and mentors.

**Comment by kytrinyx** [comment]
> perhaps we can establish some kind of nursery

I like this idea. I also really like the name "nursery"

I think that we can use the same process as now (https://github.com/exercism/request-new-language-track) but establish a clearer process and firmer criteria for actually including them on the site.

I don't think we need to have them in a separate organization—a custom repository topic, and making sure that the README reflects the state would likely be enough. I would want everything to be in the same organization for discoverability.

**Comment by tleen** [comment]
Closing in favor of overarching discussion in #191.
