### ISSUE TITLE
Running exercism in a local environment.

### ISSUE THREAD

**Issue by mattr-** [exercism/discussions#144]
Hi!

We're currently running through an elixir course at work and have been using Exercism as some supplemental exercises to the course content. During a discussion today, I brought up that Exercism doesn't really allow you add custom exercises to a particular track on the fly. During that same conversation after I said Exercism was open source, it was suggested to host it locally and then add exercises to the track.

All those words to ask a simple question: Is it possible to set up Exercism in a hostd environment, similar to how one might set up some other hosted service such as GitHub Enterprise, Jenkins, HipChat, etc.?

Thanks! :heart:

**Comment by Insti** [comment]
Yes.

Start here:  https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md

**Comment by Insti** [comment]
If you need any help setting it up try the gitter dev chatroom: https://gitter.im/exercism/dev

**Comment by mattr-** [comment]
Ideally we'd want to use our own instance of GH:E for the oauth flow, disable the seed users, etc. I guess that's probably not supported out of the box though.

**Comment by Insti** [comment]
I'm not aware of anyone having done that before.
@kytrinyx will know more.

**Comment by kytrinyx** [comment]
> Ideally we'd want to use our own instance of GH:E for the oauth flow

Yeah, some professors are running their own instance of this. I'm pretty sure you just need to set the environment variable for the GitHub token or app or whatever it is. (key + secret maybe?)

**Comment by mattr-** [comment]
>I'm pretty sure you just need to set the environment variable for the GitHub token or app or whatever it is. (key + secret maybe?)

Perfect. I'll dig around a little bit and see what I can come up with. Thanks!

**Comment by kytrinyx** [comment]
I don't know how to categorize this request. It's not about the user-facing product directly, so concerning/product is not the right thing. But it's not really about the open source project (maintenance, contribution, etc...) either. Sorry about the label noise!

@mattr- This wasn't mentioned explicitly, but we're working on a full redesign of the user-facing product (see https://github.com/exercism/docs/blob/master/roadmap.md#the-product for details).

I'm going to go ahead and close this, since I _think_ we've answered the question. If not, feel free to reopen it with more details.

**Comment by mattr-** [comment]
Thanks everybody for the help! :heart: The initial need for this seems to have died but it's good to know that others have done it and it can be done. If this is something the company I work for ends up doing, I'll have some good material for a blog post to share with y'all later. :smiley:
