### ISSUE TITLE
Accepting Team Membership Request

### ISSUE THREAD

**Issue by pmbanugo** [exercism/discussions#164]
Hi! In order to accept a request to join a team, the current process is:

1. Click the Notification Icon (which take me to the notification page)
2. Redirects to notification page and show a list of request to join my team.
3. Click "Accept" on a particular user request. 
4. Redirects to the team profile page asking me to edit or update team info
5. Repeat steps 1 through 4 if there are multiple requests to accept.

So for me, I'd like it to avoid the redirect on step 4. I'll suggest using Ajax to process the request and show a lightweight notification and either remove the user from the list or take out the two buttons beside it. This allows me to stay within the flow of accepting user request and not deciding for me to edit the team profile :) 

Thank You!

**Comment by kytrinyx** [comment]
That would be a nice improvement, indeed, thanks @pmbanugo!

As a tangent, we're in the process of completely redesigning the website and the user experience will be much, much smoother across the board in the new one. That said, this seems like a pretty small change, so if someone has some spare cycles it would be a nice improvement.

**Comment by kntsoriano** [comment]
Hi,

I've started working on this problem, and I've encountered a few problems while working on it.

1. Since this problem deals with AJAX, I decided to add browser testing via Selenium. Am I correct in the correct path taking this approach? I see some code that deals with AJAX, how are those tested?
2. Since we're doing everything via the front end also, 2 things also need to be updated: (1) The notifications count as the `<title>` of the page. (2) The notifications count as the header of the page.

With these problems, I'm sort of inclined to do a solution instead where clicking "Accept" or "Decline" redirects to the notification page instead of the team page. I'm just not sure whether that really solves the problem.

**Comment by kytrinyx** [comment]
@kntsoriano Thanks so much for thinking of testing. I believe that for previous Ajax-y things, we tested the javascript function itself, but didn't test the integration. I'd be comfortable doing that here if you are.

For the notification count, how about adding an endpoint that returns the count from within `app` and then updating it within the page? I might be misunderstanding the flow you're working towards, so please tell me if I'm completely off base!

**Comment by kytrinyx** [comment]
I'm going to close this as we're redoing teams from scratch in the new site.
