### ISSUE TITLE
Putting maintainers bios on the new website

### ISSUE THREAD

**Issue by iHiD** [exercism/discussions#168]
#172 Hello @exercism/track-maintainers!

As part of the new website we want to make a big deal about how awesome you all are! :) Your details will appear on the track pages, along with any mentors for that track.

I'd like to propose adding the following to a track's `config.json` file.

```
"maintainers": [
  {
    "github_username": "iHiD",
    "active": true,
    "show_on_website": true,
    "name": "Jeremy Walker",
    "bio": "I'm a geek",
    "link_text": "My Website",
    "link_url": "http://ihid.co.uk",
    "avatar_url": null,
  }
]
```

- `active` signifies whether this person is an active maintainer or an allumni
- `show_on_website` signifies whether this profile should appear on website
- We will download the avatar from your `avatar_url` location and host it on Exercism. If it is `null` (or key missing) we will use your github avatar.
- If `name` is `null` we will use your Github name.
- `link_text` and `link_url` are a pair that allow you to showcase any link of your choice. If it is missing or `null` we will use your Github link.
- `bio` will probably need a char limit of something on it but I need to work that out. If it is missing or `null` we will use your Github bio.

Does anyone have any objections to this format, or anything else they feel should be added? Thanks.

**Comment by kytrinyx** [comment]
> Your details will appear on the track pages, along with any mentors for that track.

I think we should allow for people to opt out (I don't see this as a common thing, but I don't want to put pressure on folks)

**Comment by iHiD** [comment]
Great point. Let's add `public`: `true` too.

**Comment by yurrriq** [comment]
LGTM

**Comment by verdammelt** [comment]
While I think publicizing my involvement might be detrimental to my track ;) This seems good. Especially if there is an opt-out.

**Comment by tejasbubane** [comment]
I think we should also link to their exercism profile - that way others (especially beginners) can look up their solutions and learn.

**Comment by ErikSchierboom** [comment]
Good idea! +1

**Comment by rbasso** [comment]
> As part of the new website we want to make a big deal about how awesome you all are! :)
>
> Your details will appear on the track pages, along with any mentors for that track.

I'm in favor or against it, but what is the goal in doing that? What it the expected effect?

**Comment by ErikSchierboom** [comment]
> I'm in favor or against it, but what is the goal in doing that? What it the expected effect?

Well, I'm guessing this is because most people enjoy showing that they are involved working on a project. As such, this could perhaps increase the happiness of maintainers, which might currently not be appreciated as much by the general public as they perhaps should. I don't know if this is change will fix all this, but I do think it can help.

**Comment by iHiD** [comment]
> what is the goal in doing that? What it the expected effect?

It has two purposes. The first, as @ErikSchierboom says is that it helps showcase the hard work of maintainers and raising their profile, which gives them a way of getting some small thing back for all their effort. The second is that Exercism is fundamentally about community. Highlighting key members of that community (e.g. maintainers and mentors) is key to encourage other people to get more involved.

**Comment by NobbZ** [comment]
> Great point. Let's add `public`: `true` too.

Thats not an option. That's not opting out, but only hiding information. It will still be accessible in the repository publicly.

If one does not wan't to be visible with his full bio, he will just not be in that file.

**Comment by iHiD** [comment]
Thank you all for your comments. I've updated the initial post with the agreed format. @kytrinyx Could you add this to the configlit too pls? Thanks :)

**Comment by NobbZ** [comment]
It feels like some valid statements haven't been considered.

It has been proposed to not use `config.json` but another file for this to avoid further cluttering of the JSON file and also to avoid potential merge conflicts. Instead of putting more and more into it, I'd try to extract even more into different files, but this is definitively worth another ticket/discussion.

Also I still think, that `show_on_website` or whatever you call it is a farce as long as the repositories containing the data are publicly available.

**Comment by iHiD** [comment]
@NobbZ - sorry that you feel that statements haven't been considered.

> Also I still think, that show_on_website or whatever you call it is a farce as long as the repositories containing the data are publicly available.

I can see people who might want a record of their involvement in the github world, but not on the exercism website. I don't see what damage `show_on_website` does. Can you show me a use-case where this causes you pain please? 

Also, while I understand that this grates with you, using words like "farce" is not conducive to a discussion where everyone's opinions should be valued. From the dictionary, "farce" is defined as "a comic dramatic work using buffoonery and horseplay and typically including crude characterization and ludicrously improbable situations." Please choose your words more respectfully.

> It has been proposed to not use config.json but another file for this to avoid further cluttering of the JSON file and also to avoid potential merge conflicts. Instead of putting more and more into it, I'd try to extract even more into different files, but this is definitively worth another ticket/discussion.

At the moment, we have a lot of tooling around this specific file - listening for changes to it, checking that it's in a good state, etc. I'm keen to not have to rewrite or overly modify that code in order to be able implement this. However, I agree that splitting that across multiple files (e.g.`exercises.json` and `maintainers.json`) might be a good move. If you feel that's worth another discussion, I'll leave you to start it.  @rchavarria - Sorry I missed your point on this.

**Comment by rbasso** [comment]
@iHiD wrote:
 
> I can see people who might want a record of their involvement in the github world, but not on the exercism website. I don't see what damage show_on_website does. Can you show me a use-case where this causes you pain please?

Could you show me a use case where `show_on_website` is needed? Why would we include in a file information that will not be used?

Another question: How to deal with unavailable maintainer's information?

**Comment by NobbZ** [comment]
If I wan't to have my effort visible in github, I do not need to do anything, if I do not want it to be visible at github I must not contribute. I can already make my bio and even more publicly available in my github profile, also my contributions to a certain repository will be visible for an eternity through the repository statisitcs. eg. the erlang track: https://github.com/exercism/erlang/graphs/contributors You will even get ranked against other contributors and you can't opt out there.

So keeping my bio up to date in a tracks config when I do wan't to keep it on github, it puts a burden on me to double maintain my bio on github.

I do accept the burden of double maintaining the data, when it is supposed to be displayed at different places.

This burden of double maintainership is the "harm" I do actually see.

----

Also I do wan't to apologize my wording. In germany the direct translation of "farce" is used much more liberally than in english as it seems. We use it for nearly all small things, that solely exist hide the actuall bigger "problem".

**Comment by iHiD** [comment]
@rbasso By committing to a track, you've already made your relationship with exercism permanently public (via Github), so not being in this file gives you zero extra privacy. However, you might want to explicitly say you don't want to appear on the Exercism website, and add your github_username and a `show_on_website` flag as false. This means that other maintainers won't add you to this block thinking they're being nice but actually annoying you.

This flag gives us flexibility, which strikes me as wise. However, if the consensus is that people just don't want that in there, that's fine by me. However, the fact that people seem to be able to want to opt-out (see 👍s on Katrina's post) suggested to me that an explicit mechanism for this would be good.

**Comment by iHiD** [comment]
> So keeping my bio up to date in a tracks config when I do wan't to keep it on github, it puts a burden on me to double maintain my bio on github.

@NobbZ  If you are a maintainer on Ruby and on Python, you might want different bios for each track, explaining your background in those specific languages. 

Github != Exercism. In the same way you don't have a link between your Twitter bio and your Github bio, I don't feel it's right that we should have an explicit link between your Github bio and your Exercism bio.

If you don't care about appearing on the Exercism site and just want to appear on Github, then you can just leave your block off the maintainers track, or your name there and explicitly say you're not going to be on the website. You then don't have to maintain anything.

**Comment by rbasso** [comment]
@iHiD wrote:

> By committing to a track, you've already made your relationship with exercism permanently public (via Github), so not being in this file gives you zero extra privacy.

My comment has little to do with privacy. I'm just arguing against some design decisions.

Let me try to be more clear!

When a maintainer commits, they supply the github account name, their name and, usually, an e-mail address for contact. The following information is not available but seems demanded by your proposal:

- `bio`
- `link_text`
- `link_url`
- `avatar_url`

It is undesirable to force the maintainers to supply/updated the demanded data on the tracks they maintain, and it is also impossible to create this data from nothing.

Unless the entries are filled with fake/empty data, I have to assume that a maintainer may or may not be present in the file, which seems to be the case, as you explained to @NobbZ:

> If you don't care about appearing on the Exercism site and just want to appear on Github, then you can just leave your block off the maintainers track, or your name there and explicitly say you're not going to be on the website. You then don't have to maintain anything.

So we have two ways to opt-out from appearing in the Exercism website:

- Missing maintainer's block.
- `show_on_website: false`

I'm having a hard time imagining why would a maintainer prefer the second option!

Now that it is clear that we don't have to opt-out explicitly, I don't really care about `show_on_website`.

> Github != Exercism. In the same way you don't have a link between your Twitter bio and your Github bio, I don't feel it's right that we should have an explicit link between your Github bio and your Exercism bio.

Not sure if the analogy holds here, because Exercism demands a GitHub account to identify the user. Right?

@NobbZ wrote:

> So keeping my bio up to date in a tracks config when I do wan't to keep it on github, it puts a burden on me to double maintain my bio on github.

I also don't like the idea of manually synchronizing multiple profiles...
 
This happens because this proposal reproduces part of the functionality of GitHub's Public Profile and Team's Members View, while allowing distinct profiles for each tracks, which @iHiD seems to considers desirable.

I would definitely prefer if it could use GitHub's data directly, because that would avoid the problem of synchronizing this new list of maintainers with the actual maintainers in the corresponding team. The way it is now, I think it will bring more troubles than benefits.

Anyway, in a do-ocracy, the ones that will implement and carry the burden of maintaining it should decide. 👍

**Comment by ijanos** [comment]
I noticed there is no `email` field. Why not include it? It could be used with [Gravatar](https://gravatar.com) then the `avatar_url` could be omitted.

**Comment by tleen** [comment]
> I noticed there is no email field. Why not include it? It could be used with Gravatar then the avatar_url could be omitted.

I would prefer to avoid adding another service required to have a profile on the site. Would much rather:

1. It be automagically linked to my GitHub avatar or
2. Have it be an arbitrary URL I can set myself.

**Comment by iHiD** [comment]
> I noticed there is no email field. Why not include it? It could be used with Gravatar then the avatar_url could be omitted.

I suggested in my initial post: "If it is null (or key missing) we will use your github avatar."

**Comment by iHiD** [comment]
> I would definitely prefer if it could use GitHub's data directly, because that would avoid the problem of synchronizing this new list of maintainers with the actual maintainers in the corresponding team. The way it is now, I think it will bring more troubles than benefits.

I'm happy to derive your bio and link from your github profile too, if those fields are missing or null.

**Comment by kytrinyx** [comment]
I apologize for not weighing in here before this. There's a lot to dig into here.

@rchavarria I think your point about merge conflicts is a very good one, and something I think we should consider.

I do not think that having multiple files (especially if they are for different purposes) is a problem. We can easily tweak tooling to work with those files, and as long as we document their purpose and format I don't see a problem with this.

> Not sure if the analogy holds here, because Exercism demands a GitHub account to identify the user. Right?

@rbasso no, not in the new website. I made that choice early on because I was lazy and didn't want to implement user accounts explicitly.

> I noticed there is no email field. Why not include it? 

@ijanos I would rather not encourage people to email maintainers directly. If you absolutely want to email someone, check their GitHub profile for a public email address. I'd prefer it if we encourage people (subtly) to open issues on GitHub. I get a ton of email from people that would be more appropriate as issues on GitHub.

> [email] could be used with Gravatar

I'd rather not tie this even further to third party services. The avatar field is optional, we'll use your GitHub avatar if it's null.

It sounds like we have have three questions to resolve:

**Would maintainers (in general) like the option to appear as such on the Exercism website?**

I'd like to clarify that this isn't just a copy of your GitHub bio etc, this is much more targeted at showing your experience or involvement with a particular language or track. Also, this isn't about being public or not, open source activity on GitHub is public, we're not going to change that. This is about having your avatar, username, maybe name, and a custom bio appear on the track page for a language.

**If so, what data is useful?**

I personally don't think an email is necessary. I have no need to link to any other website outside of Exercism, but I could see where others might. If I were still helping maintain the Go track and the Ruby track, I would want separate bios there, because my involvement in those language communities have been quite different.

**How do we structure and maintain that data?**

The maintenance of that data is separate from the question of whether or not maintainers can be featured on the site. If we think that it's a good idea to have maintainers on the site, then let's talk about what data makes sense, and how to minimize the maintenance burden of it.

As part of maintenance, I wouldn't mind being able to generate the data for the maintainers based on current team membership in such a way that by default _nobody shows up on the website_, and that each person can individually opt in, both making it easy to update the fields that you want to update, and refraining from doing so if you opt out.

I have to run to a meeting, but will come back to this later today to see if I missed any points.

**Comment by ErikSchierboom** [comment]
> I would rather not encourage people to email maintainers directly. If you absolutely want to email someone, check their GitHub profile for a public email address. I'd prefer it if we encourage people (subtly) to open issues on GitHub. I get a ton of email from people that would be more appropriate as issues on GitHub.

This. Please don't list the e-mail, having people contact individual maintainers completely bypasses the GitHub issues way we deal with tracks.

**Comment by kytrinyx** [comment]
One of the things that I've learned in the past year is that making people feel _real_ has a huge impact on empathy. In open source, the difference between a faceless maintainer and a maintainer that you connect to changes how people think about you, interact with your project, and how willing they are to make allowances for your constraints.

As such, I think that it would be a valuable thing to feature Exercism maintainers on the website. This has three purposes (rather than the two stated above).

1. provide a stronger basis for empathy with maintainers
1. give well-deserved recognition
1. plant a seed that "exercism tracks are maintained by people like me... _I could do that!_"

**Comment by NobbZ** [comment]
> If you don't care about appearing on the Exercism site and just want to appear on Github, then you can just leave your block off the maintainers track, or your name there and explicitly say you're not going to be on the website. You then don't have to maintain anything.

This explanation does actually makes sense to me.

The way as I understood it first was, that I **have to** fill out all the data. But setting `show_on_website` to false and omitting everything else is a fine way to say "I do not wan't to get displayed now or in the future", while omitting the entry completely could be as "he did not care" and may be filled in by other individuals postmortem to honor the person.

So I do see sense in that flag now.

Besides of that, I'd be glad to provide bio as soon as `configlet` and the webpage can handle them ;)

**Comment by kytrinyx** [comment]
> The way as I understood it first was, that I have to fill out all the data.

Yeah, we would totally just generate everyone with `show_on_website` false, that way whoever doesn't want to be displayed could just ignore it all.

**Comment by tleen** [comment]
A little devil's advocate on this, is there a drawback to listing maintainers? 

The only one I can think of off the top of my head is that it may discourage feedback from other users. A user may see a maintainer's comment on their submission and think that it may carry more weight than it should. It could discourage a back and forth if they take it more like a "well *they* must know what is right here they maintain this track". I also think it could shutdown discussion on your own submissions for the same reason. 

Since you don't have to be listed that may something for the individual maintainers to weigh.

**Comment by iHiD** [comment]
> Another question: How to deal with unavailable maintainer's information?

Generating everyone with `show_on_website` to `false` and then allowing maintainers to change that to `true` and provide their info gets us there. If someone is unavailable, I'm presuming that's because they're not active? Or is there another time that might be true (beyond a week's holiday etc).

> The only one I can think of off the top of my head is that it may discourage feedback from other users.

@tleen - In the new version of Exercism, only mentors will be able to give feedback to users.  ([Discussion here](https://github.com/exercism/discussions/issues/154)). Also, maintainers and mentors are different sets of users (although of course a maintainer might also choose to be a mentor). 

Saying that, your concern still makes sense in new exercism where a maintainer is a mentor. The list of maintainers won't be showed during the actual learning journey part (only on the overall public-facing track pages) and we weren't planning on flagging that on the discussion page, so I don't think it's likely someone would realise that their mentor is also a maintainer, so hopefully this shouldn't be an issue. But thank you for raising it. Anything I've missed?

**Comment by NobbZ** [comment]
> Yeah, we would totally just generate everyone with `show_on_website` false, that way whoever doesn't want to be displayed could just ignore it all.

At least we really should do it for everyone who has contributed so far/has been official a maintainer and retreated/disappeared. When they were still part of the engine, there wasn't such a feature in sight, and perhaps they never had contributed if they knew that it will be listed somewhere outside of github.

If we can still contact those ex-maintainers, then we can explain and they can decide if and which data they wan't to provide.

**Comment by kytrinyx** [comment]
> At least we really should do it for everyone who has contributed so far/has been official a maintainer and retreated/disappeared.

Yeah, that sounds good, @NobbZ

**Comment by ijanos** [comment]
Ok, I agree with not listing the email. If you link my github profile it will be available with one indirection anyways, but yeah, I prefer not being emailed :) 

I was thinking about the maintainer list, if I understand correctly it will be basically this list: https://github.com/orgs/exercism/people 

People can choose public or private here already. A new maintainer list will duplicate this, right?

**Comment by kytrinyx** [comment]
> A new maintainer list will duplicate this, right?

This would be focused on putting the maintainers on the Exercism website, on the pages of the respective tracks. It is not duplication as such.

**Comment by kytrinyx** [comment]
Ok, having gone through this again, here's what I'm proposing:

I think we should use a separate `maintainers.json` file, due to
* the issue with getting conflicts in the `config.json`
* some automation that I'm working on to let tracks manage memberships in the GitHub team that has commit on the track

For the format, I'm suggesting that we use the following (example):

```
{
  "github_username": "iHiD",
  "show_on_website": false,
  "alumnus": false,
  "name": "Jeremy Walker",
  "bio": "A friendly, detailed description of your background/interest in the language, to go on the Exercism track page.",
  "link_text": "My Website",
  "link_url": "http://ihid.co.uk",
  "avatar_url": "http://example.com/iHiD.png",
}
```

The only two required fields are:

- `github_username`
- `show_on_website`

Optional fields:

- `alumnus`: defaults to false if absent
- `avatar_url`: defaults to your GitHub avatar if `null` or absent.
- `name`: defaults to whatever your public display name on GitHub is. If you have not filled in this field, and there is no name defined on your GitHub profile, we will use your GitHub username as your display name.
- `bio`: if null or absent, it defaults to your public GitHub bio (note that I don't think this is a great default, I would much rather have a bio that is specific to the track). If this is an empty string we will not show a bio at all.
- `link_text`: no default. If absent we will use the `link_url` as the anchor.
- `link_url`: no default. If absent we will not show a URL.

If there are no major disagreements, I'll go ahead and generate this for each track, setting `show_on_website` to false. Then anyone who wants to be featured on the website can update this.

**Comment by tleen** [comment]
Where is this file to live? Are you thinking in track root or down in /config?

**Comment by kytrinyx** [comment]
@tleen excellent question. I think `/config` makes sense.

**Comment by ErikSchierboom** [comment]
Sounds good!

**Comment by kytrinyx** [comment]
Check out https://github.com/exercism/smalltalk/pull/19 for a sample of the PR that I intend to submit (unless someone proposes a strong reason to do something different than this).

**Comment by kytrinyx** [comment]
I've submitted some "canary" PRs to get early feedback on this format (Rust, Haskell, Erlang, Ruby), they're linked from the tracking issue in "meta" (listed above).

**Comment by kytrinyx** [comment]
Thanks for helping hash out the details on this one. We're still going to need bios, but they can trickle in as we go along.
