### ISSUE TITLE
Exposing team activity via private share url

### ISSUE THREAD

**Issue by tmikoss** [exercism/discussions#171]
Are there any plans to expose team activity in a way not protected by github auth?

My colleagues are using exercism tracks as a monthly "check out a new language" exercise. We all have joined a team on the site, but would like to have more functionality not provided by the page. Things like voting for the next track to tackle, setting and tracking goals. 

To this end, I'd like to build an external app that queries exercism for team activity stream. However, scraping a github-auth protected web page is less than ideal. Could the team activity page be exposed via private share url, much like individual profiles are? 

The ideal would be some kind of API for external integrations, but adding a private share url seems to be much smaller feature.

PS The same result could already be achieved by having team members register their profile page private share urls with the external app, but I imagine that would place a greater load on the exercism.io site, as well as make the external app less pleasant to use.

**Comment by kytrinyx** [comment]
@tmikoss I see that you got pulled into the discussion about teams. The most useful thing I can say about this right now is that we're trying to figure out what people are using teams for so that we can better design a solution that solves that problem, rather than assuming that what we have is what people need and then trying to tweak (or shoehorn) it into being useful.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as we are launching an all-new teams design shortly (ETA 1-2 weeks).
