### ISSUE TITLE
Introductory copy for tracks

### ISSUE THREAD

**Issue by iHiD** [exercism/discussions#173]
Hi @exercism/track-maintainers. As part of nextercism, we have shiny new track pages, which will look something like this:

<img width="791" alt="screen shot 2017-07-22 at 20 37 41" src="https://user-images.githubusercontent.com/286476/28494130-9e5e42e6-6f1d-11e7-8273-0960c4e298c7.png">

To make this happen, there are three things that we need to make sure all tracks have in an agreed format:

1) The blurb that appears underneath "`$LANGUAGE` Track" in the header. The aim of this is to give someone a really quick feel for what the language is about and why it might appeal to them. This should be a couple of sentences totalling ~30 words and will be plain text (not markdown). I propose storing this as a string in `config.json`

2) The "About `$LANGUAGE`" text. This provides a bit more detail about the language. It might talk about its history, design goals, or about what the language is a great fit for, etc. This should be 70-120 words split over 1-3 paragraphs. This text should be a friendly, genuine sales pitch for why someone should learn a language. It should not be an in-depth introduction, and it should not be a quote from another source, though it can certainly point people to other sources if they want to learn more. It can be in markdown format, but should only contain links and emphasis (bold, italic). I propose updating the `ABOUT.md` files to fit this format.

3) The code sample that appears in the frame on the right-hand side, next to "About `$LANGUAGE`". This provides, at a glance, the style of the language. It needs to be 6-10 lines long and <=40 chars per line. I propose storing that in `docs/SNIPPET.txt` and if that file doesn't exist using first 10 lines of the first core exercises (which will normally be hello-world).

If you thoughts or suggestions we'd love to hear them. If you think this all sounds fine and you don't have anything specific to add, please 👍 this post.

**Comment by IanWhitney** [comment]
Any limits on line length in the snippet?

**Comment by iHiD** [comment]
@IanWhitney Thanks for checking. 6-10 lines, <=40 chars per line. Updating the main post to reflect this.

**Comment by masters3d** [comment]
This information is already on the repo? 
https://github.com/exercism/swift/blob/master/docs/ABOUT.md


1. Could the blurb be just the beginning of the ABOUT?
2. A mark down version is more accesible to update. This copy is hard to maintain  because everybody has different opinios on what should be here. https://github.com/exercism/swift/pull/277
I think this should come from an official source like the Lang webpage or a Wikipedia entrie. If somebody doesn't like it then they can change it on their repo about md file or submit a change to Wikipedia. 
3. Can we use the HelloWorld example code here? Most if not all tracks have a hello 

Copy is hard to maintain.

**Comment by kytrinyx** [comment]
@masters3d 



> This information is already on the repo?

Yes, we're suggesting using that file, though I think a lot of tracks will need to edit it to make it a better fit for the new site.

> Could the blurb be just the beginning of the ABOUT?

Not really, in my opinion. The first sentence of 3 paragraphs is often not really a proper high-level summary.

> A mark down version is more accessible to update.

The blurb needs to not be markdown, because anything other than plain text would break the design. We don't _want_ to support links or images or lists or any other things in the blurb. We just want it to be a short pitch about the language.

> This copy is hard to maintain because everybody has different opinios on what should be here.

Yes, and on the current site that makes sense, because we have not had a clear philosophy about _why_ we have that intro.

On the nextercism site we have a lot clearer guidelines about the goal of that copy.

> I think this should come from an official source like the Lang webpage or a Wikipedia entrie. If somebody doesn't like it then they can change it on their repo about md file or submit a change to Wikipedia

No, this should really not be from some other source. Other websites have other purposes. Exercism's track page is about giving people a friendly, welcoming, enticing reason why they should care enough about the language to try it out. This can _link_ to other sites, certainly, if people want more information but I think it would be quite off-putting for this copy to be a quote from a site whose purpose is not the same as ours. And I don't know of any sites whose purpose is the same.

> Can we use the HelloWorld example code here? Most if not all tracks have a hello

Yes, that's what we're suggesting. If they don't have a hello world, we can use the example code for the first exercise whatever it is. You would only have to put a `docs/SNIPPET.txt` if you for some reason don't think that the first exercise in your track is a good fit.

> Copy is hard to maintain.

No, copy is hard to write in the first place :)

This isn't like documentation that gets out of date quickly because APIs change. Languages don't really change their philosophy, history, problem areas that they're a good fit for on a regular basis.

I think it's worth writing custom copy that will help make the tracks shine. Once we have something, I don't anticipate it becoming a burden to maintain.

**Comment by ErikSchierboom** [comment]
I agree with all three proposed points. As an addition, I must say I *really* like the design. It looks great!

**Comment by NobbZ** [comment]
I agree with the made points as well, though it might be hard for non-native speakers to come up with appropriate content for the blurb or the about.

**Comment by robphoenix** [comment]
@NobbZ more than happy to help proof read any text. And I second @ErikSchierboom the design is sweeeeeeet!

**Comment by kytrinyx** [comment]
I'm also happy to help proof-read content for the blurb and the about. I'd suggest pinging whoever volunteers to help proofread with specific `@`mentions in the PR.

**Comment by rpottsoh** [comment]
1.  It isn't clear to me where `blurb` is stored.  @iHiD proposes storing it as a string in `config.json`.  I am not clear how this should appear in `config.json` if this is the consensus.

2.  Where should the `About` information for the track be stored.  @iHiD proposes updating the `About.md`.  Just want to confirm that the consensus is to update the `ABOUT.md`.  Is it OK to go ahead and merge an updated `ABOUT.md` while the old site is still active?

3.  In more than one instance above `docs/SNIPPET.txt` is mentioned as the location for the code sample so I will go with that.

I think I can proceed with items 2 and 3 above, but item 1 is not clear to me.

**Comment by rpottsoh** [comment]
Sorry about all that....  exercism/go#795 has cleared up my confusion.

**Comment by kiliankoe** [comment]
As someone who's been reading and enjoying the Behind the Scenes newsletters but not following along elsewhere, I just want to add that that screenshot looks fantastic 😍! Can't wait to try out the new version!

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as the new prototype is up for maintainers, contributors, and current Exercism users.

If you want to help update some of the ABOUT docs, please check out this tracking issue: https://github.com/exercism/meta/issues/85
