### ISSUE TITLE
Turning on branch protection for all tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#174]
### Background

 A couple of months ago @nicolechalmers started doing sketches, designs, and wireframes based on the [design documents](https://github.com/exercism/docs/blob/master/about/conception/README.md) that Thalamus and I have spent the past 6+ months working on. More recently, @ccare and @iHiD started implementing a prototype based on those designs. We've made some design decisions that we believe will be a vast improvement over the current website, particularly with respect to how changes in track repositories are reflected on the site.

### Current Situation

In the current website, track repositories are all submodules in a Ruby gem which has some additional logic related to tracks and exercises. This means that we need to

- ... in the gem:
  - update all the submodules
  - bump the version
  - publish a new version to rubygems
- ... in the website (_and_ the api):
  - update the version of the gem in the lockfile
  - commit
  - deploy

In other words, this involves committing to three different repositories and deploying two different codebases.

There are a lot of places where this can go wrong, not to mention _I have to actually deploy_. Sometimes I get busy, and which point all the hard work that all the maintainers do gets held up.

That's not acceptable.

### Changes in Nextercism

In the nextercism prototype we're working directly with the tracks' git repositories themselves. We will be updating these continuously, so any changes to the tracks should be reflected on the website near-instantaneously (well, it might take a minute, but probably not much longer than that. Compared to the day-to-week lag that you all are used to operating with, this will probably feel like a bit of a miracle).

On the other hand, this means that if we screw up master in any way on a track, that will be reflected on the website immediately.

### Proposal

So. In order to protect the website I wish to turn on branch protection for the master branch of all tracks. That will mean that:

- master cannot be pushed to directly
- before they can be merged, all pull requests must
  - have at least one approval
  - have a passing build
  - be up-to-date with master

This means that even trivial changes will need to go into a branch and a pull request, and be approved by one of the other maintainers.

This might be a little bit annoying, but I think it's worth it.

If you have any counter-arguments or can think of anything I've missed, or other ways to protect the website from bad changes, I'd love to hear your thoughts.

If you think this seems reasonable but don't have anything to add to the discussion, please add a 👍 reaction.

**Comment by rpottsoh** [comment]
Are there any tracks with a single maintainer / mentor that would not have anyone to approve their PRs?   Overall what you propose sounds fine.

**Comment by kytrinyx** [comment]
There are quite a few tracks where that is a problem.

I'm working on a dashboard to help with this, and am hoping to make a team of "guardians" who can help mitigate the problem until we can actively go find more maintainers for these tracks.

**Comment by petertseng** [comment]
> * master cannot be pushed to directly
> * before they can be merged, all pull requests must
>     * have at least one approval
>     * have a passing build

My support with no reservations

> * be up-to-date with master

My historically bad experiences with this setting cause me to wish it were not necessary, but I know that it is. I have no better suggestion that still achieves the desired goal. My support, with a wish that things could be better:

I wish the up-to-date setting could take advantage of the fact that Travis CI checks the result of merging each PR with master, but that does not help when there are N PRs that were made simultaneously since then the result of merging them with each other is not checked unless the builds are explicitly restarted after each one is merged.

Therefore, if I could make a feature suggestion for GitHub, it would be to detect whether Travis CI's merge check was against an up-to-date master, as an alternative to having the branch be based off an up-to-date master.

Since I see the setting is a necessary one, when it is a problem (>= 3 PRs simultaneously in flight) I have historically dealt with the problem by octomerging. It might be the case that I will be doing that a lot more in the future. It would therefore also be interesting if GitHub had a UI for octomerges... but that seems very unlikely, given their increased complexity. No feature requested listed in this comment is a blocker for requiring up-to-date branches.

**Comment by petertseng** [comment]
EBWODP: My suggestion about the Travis CI was ordered: "Suggestion, problem with my suggestion (doesn't help with N PRs in flight), make the suggestion again without solving the problem". I combined the two suggestion portions and clarified that they are still subject to the problem.

**Comment by kytrinyx** [comment]
@petertseng these are all great observations.

> I wish the up-to-date setting could take advantage of the fact that Travis CI checks the result of merging each PR with master. Therefore, if I could make a feature suggestion for GitHub, it would be to detect whether Travis CI's merge check was against an up-to-date master, as an alternative to having the branch be based off an up-to-date master.

One of the problems with this is that this is an external integration. The only part of this that is under GitHub's control is the final status of, not what happens to set that status (e.g. you could have a bot that sets a green check mark and says _your commits are bananas!_, and all GitHub knows is that the status is good).

Now... we could likely write some automation around this if we wanted to, given that we know which exact part of the Travis integration we care about.

That said, the N PRs in flight thing is a problem and we've actually run into this where two PRs both pass the tests individually and against master, but are incompatible with each other.

So yeah. I see your point, and I also don't see an immediate way around that. I am going to think about whether we could write an automation for the case that you describe, though.

**Comment by NobbZ** [comment]
We had `master` protected for a few months on the erlang track. That has been in a time, when I was the only active maintainer. The current second active maintainer is only semi-active and learning erlang as he goes along and doesn't implement or care for new exercises, but tries to get ordering and difficulties right.

I do hope, he can help me to get the nextercism tree right.

But also, when I was the only maintainer, and we didn't even made reviews necessary, waiting for travis was quite a burden, especially when we were operating on the 5 builds limitation, because of automated mass-PRs through blazon. I often had to manually set alarms or reminders on a third party service or my mobile. I missed some of them, which really slowed everything down.

Therefore, I have to say, that this might really be a show stopper or at least slow downer for "undermaintained" tracks. Especially when we require reviews (who shall review PRs of the sole maintainer?)

We shouldn't activate this setting before it is ensured that there will always someone available for reviews!

**Comment by kotp** [comment]
I also see this as a problem on branches where there are 3 maintainers when 2 of the tree maintainers may be swamped.

Has the "social contract" of not pushing to master except for trivial commits been problematic?

As it is, only those with "maintainer" privileges are able to do so, and on the tracks that I am on, I have not seen this abused.

**Comment by kytrinyx** [comment]
> waiting for travis was quite a burden

@NobbZ This is a very good point. I'm going to think about this one for a bit.

> Has the "social contract" of not pushing to master except for trivial commits been problematic?

Not in the tracks with seasoned, experienced maintainers, no. In new tracks (without an experienced buddy), very much so.

**Comment by iHiD** [comment]
> *Has the "social contract" of not pushing to master except for* **trivial commits** *been problematic?*

I'd also add that a small mistake in a trivial commit could have a much bigger effect now. For example, someone misplacing a couple of brackets and therefore mis-structuring the `config.json` while tidying the indentation or something, could mean that half the exercises disappear from the website immediately.

Again - very unlikely with seasoned maintainers/devs (but I wouldn't always bet on myself to not make mistakes!), more likely with less experienced.

**Comment by kytrinyx** [comment]
> I wouldn't always bet on myself to not make mistakes

I *know* I don't trust myself. I'll pay close attention every single time, except the time when I... don't for some reason.

**Comment by kytrinyx** [comment]
As a side note, I'm going to take a look at what we can do to speed up Travis (use caching where possible, abort builds as soon as possible if we know we need to build a newer one, etc).

**Comment by stkent** [comment]
If you're interested, the Java (and Kotlin) tracks recently looked into ways to speed up our CI builds; see https://github.com/exercism/java/issues/410 for some discussion. https://github.com/exercism/java/issues/326 is an issue we have identified but are yet to fix; it could save significant time when the build is broken if addressed.

**Comment by iHiD** [comment]
Also - we should investigate what it would take to up the limit from 5 to x. Rust-lang has 15 according to [this post](https://internals.rust-lang.org/t/rust-lang-organization-now-has-15-concurrent-travis-ci-jobs/2964) and could pay for more. Do we know anyone at Travis we could reach out to to ask what the max free level could be, and how much it would cost to extend that?

**Comment by NobbZ** [comment]
I think it were best if @kytrinyx just asked for a sponshorship at travis. Perhaps they can tune us to 10 builds in exchange for a small badge?

**Comment by petertseng** [comment]
Update: octomerge still possible if "build branch updates" is off: https://github.com/petertseng/octotest/pull/6

**Comment by kytrinyx** [comment]
> Use a branch on a fork instead of Exercism's copy.

This is a great observation. To me it makes no difference where I make the PR from, I script everything anyway.

> I honestly think it's cleaner to use a fork anyway.

Yeah, this is a good point. I've never thought about it much. I have thought about how to clean up old branches (as evidenced here: https://splice.com/blog/cleaning-git-branches/), but not how to avoid them in the first place. I'm pretty sure I'm convinced you're right.

> Turn "build branch updates" off.

We could, but I see no reason why I (and others) shouldn't make the PRs from forks. That would solve half the problem.

> we should investigate what it would take to up the limit from 5 to x

I'll ask the folks at Travis! I want to do my homework first, though, and do all that I can to speed things up first. Then if we get some extra cycles, we'll be making them count instead of wasting them.

**Comment by kotp** [comment]
We were talking about branches as well, instead, on the Delphi track.  Having master for the base, but push / merge to Publish branch for active web display.

**Comment by kytrinyx** [comment]
> push / merge to Publish branch for active web display.

@kotp you mean for the exercism.io website?

I could see this complexity to the backend, and I'm not sure the trade-offs are worth it. I'd be open to hearing the pros/cons, though.

**Comment by kotp** [comment]
@rpottsoh has some thoughts, not quite hashed out yet, about potentially double publishing from "master" view and "published" view.  Where any changes that make it to master can be viewed before going to the 'normal' view that users are aware of.  Gives a safety check, of how everything works together before going 'live', while still in a live way.

But not really hashed out yet.

**Comment by kytrinyx** [comment]
@kotp @rpottsoh it sounds like what you're thinking about is some sort of way to verify things in a staging environment.

Rather than something that involves automatically having multiple main branches (master for staging, published for production), I would like to encourage people to think about what it would take to build a stand-alone track-visualizer that could be used with any branch on the repository on GitHub. I think that would be more light-weight and potentially more useful than a full-on staging set-up.

**Comment by rpottsoh** [comment]
> @kotp @rpottsoh it sounds like what you're thinking about is some sort of way to verify things in a staging environment.

I think so essentially.  Instead of the site pulling from Master it would instead pull from Published.  Whenever Master is updated a maintainer would go to "http://exercism.io/test/Ruby", for example, or some other flag so that the site they arrived on would be utilizing their tracks Master branch.  If no ill affects were observed the maintainer would then advance Published forward to Master....

That is the basic premise of what @kotp and I were discussing yesterday.

**Comment by kytrinyx** [comment]
My gut reaction to having a full-fledged master/published pipeline is that this sounds like a lot of work for maintainers. My suspicion is that for the most part, people will be fine with going straight to production, so long as they've reviewed the pull request. There are always _some_ changes that we're more wary of, and I'd love to find a system that lets us verify these without imposing a change across the board on our workflow.

**Comment by yurrriq** [comment]
FWIW I've had success with git hooks before, e.g. we could set it up such that you can't push to master unless the tests pass and the configlet exits with `0`.

**Comment by kytrinyx** [comment]
@yurrriq I've also had great success with git hooks—my problem with them is that it's too easy to not have everyone using them.

**Comment by yurrriq** [comment]
@kytrinyx, right. I feel like that could be a pro and a con though :smile:. Pros: simple, easy to use. Cons: simple, easy to ignore.

**Comment by kytrinyx** [comment]
@yurrriq too true! 😂

**Comment by kytrinyx** [comment]
I forked all the track repositories and then discovered that you can turn off branch updates on Travis CI.

Now I've updated all the Travis settings for all the language tracks to the following:

<img width="874" alt="screen shot 2017-07-29 at 1 30 15 pm" src="https://user-images.githubusercontent.com/276834/28747731-ef64876e-7462-11e7-9478-58f54b7d2117.png">

This should improve things somewhat.

There are some great suggestions in the Java thread that @stkent linked to (https://github.com/exercism/java/issues/410).

The two that jump out at me are:

- Fail fast. If configlet complains and is going to fail the build, then don't bother running the rest of test suite. Same for any other early change, I suppose, though sometimes it's useful to see the extent of the damage.
- Only run the tests for the exercises if some of the exercises changed (potentially also config.json, though).
- Only run the tests for the exercises that changed (ditto on config.json)

**Comment by NobbZ** [comment]
Running only those tests that seem to be necessary might be hard to detect. We had to scan the git tree since the last forking from master, see which files were altered and associate them with an exercise. Those detections might be error prone and take probably as much time as running and building the tests. 

Per my observation, often the culprit lies in downloading and compiling dependencies. For some languages we need to repeat this even per exercise. If those languages were able to use a local cache instead then a detector wouldn't need to be created anymore but tests were much faster than before. 

Some tracks even require compiling and installing a complete language (as idris), since they aren't officially supported by Travis. Those languages should be somehow ported to Travis as a possible base language.

**Comment by kytrinyx** [comment]
> We had to scan the git tree since the last forking from master, see which files were altered and associate them with an exercise. Those detections might be error prone and take probably as much time as running and building the tests.

If travis has master available we can use `git diff-tree`:

```
git diff-tree -r --name-only HEAD master
```

That shows the list of changed files.

If we don't have access to the master ref, then we could use the [List pull request files](https://developer.github.com/v3/pulls/#list-pull-requests-files) endpoint on the GitHub API to get the list of changed paths, and only run the tests if files under `./exercises/` have changed. Then further, figure out which exercises changed and run those.



> Per my observation, often the culprit lies in downloading and compiling dependencies.

True. This is certainly not a silver bullet, only something to investigate if individual test are a problem. If we're installing dependencies for each test, this could speed things up a lot.

> Some tracks even require compiling and installing a complete language (as idris), since they aren't officially supported by Travis. Those languages should be somehow ported to Travis as a possible base language.

That's a great point. Travis is open source, we could ask what it would take to add support for a language.

**Comment by NobbZ** [comment]
> That's a great point. Travis is open source, we could ask what it would take to add support for a language.

What we want is probably adding a community supported language:

https://docs.travis-ci.com/user/languages/community-supported-languages/

But as we often have problems to actually get 3 maintainers for a track, I think it will be even harder to find 3 that wan't to care for those travis images **and** the exercism track.

**Comment by kytrinyx** [comment]
> But as we often have problems to actually get 3 maintainers for a track, I think it will be even harder to find 3 that wan't to care for those travis images and the exercism track.

Yeah, I think maybe we should just live with this for now, and see what other things we can optimize.

**Comment by ErikSchierboom** [comment]
> Are there any tracks with a single maintainer / mentor that would not have anyone to approve their PRs? 

> I'm working on a dashboard to help with this, and am hoping to make a team of "guardians" who can help mitigate the problem until we can actively go find more maintainers for these tracks.

Good to hear, as the C# and F# tracks have this problem.

**Comment by dsudia** [comment]
I'd be very happy with
* be up-to-date with master
* cannot push directly to master

and I'd be fine with the approval as long as there is that guardian system in place.

Even for a single maintainer going through the PR process can be useful just to make sure things get put through the CI system and aren't broken.

**Comment by kytrinyx** [comment]
I think in the first pass I'm going to settle for the first two and not require review.

Then once we're sure that we have a good system in place for making sure things don't ever end up unreviewed, we can consider requiring approval.

**Comment by petertseng** [comment]
> Now I've updated all the Travis settings for all the language tracks to the following:
> (an image with "Build branch updates" off)

I'm sorry, but I've received reports from https://github.com/exercism/dart/pull/35, and I believe the reports to be correct, that this causes updates to the master branch to not be built.

I present this supporting evidence.

* Haskell
  * https://travis-ci.org/exercism/haskell/branches tells me that https://travis-ci.org/exercism/haskell/builds/257551122 is the most recent build on the master branch, on 2017-07-26.
  * But https://github.com/exercism/haskell/commit/bdba3bdc19ed07b27b9904d60f14d74f2a37b0d3 is the latest commit on the master branch, made 2017-09-08
* Rust
  * https://travis-ci.org/exercism/rust/branches tells me that https://travis-ci.org/exercism/rust/builds/258428631 is the most recent build on the master branch, on 2017-07-28.
  * But https://github.com/exercism/rust/commit/207aee1fe022774a224d058e224bd7c32a16ac58 is the latest commit on the master branch, made 2017-09-19
* Ceylon
  * https://travis-ci.org/exercism/ceylon/branches tells me that https://travis-ci.org/exercism/ceylon/builds/258901786 is the most recent build on the master branch, on 2017-07-29.
  * But https://github.com/exercism/ceylon/commit/1cf71a2dd8789ea3a071e718a1fa8d2ac40ac5d2 is the latest commit on the master branch, made 2017-09-15

So, what are we to do?

Do we find it desirable to build the master branch?

* The answer might be "No, it's not necessary". We could content ourselves with the PR build of each PR, since it builds the result of merging the PR to master.
* My answer is "well, but I still want to make sure by building master from time to time"
  * Thanks to @bdw429s I'm told I can manually trigger a build at any time. This could be acceptable, if I had to do manual work every time I wished for one.

I kind of want to not do the manual work each time. I think I would like "Build branch updates" to be turned on again. I therefore propose it. (And have enacted the proposal for the three tracks mentioned above, but you should tell me if I should not)

If the reason to turn it off is the original reason in https://github.com/exercism/discussions/issues/174#issuecomment-317504971 of "don't want two builds per PR", then I reiterate my suggestion of making PRs from a personal fork rather than on Exercism's copy of the repository.

**Comment by petertseng** [comment]
Let's say the suggestion is taken. "Build branch updates" is turned on, and then PRs are made from personal forks to avoid building twice. However, if a PR is being made to every repo and while some PRs are still being built, others get merged to master. That, being an update to master, will trigger a build when it otherwise would not have. Please take that disadvantage into account when deciding on the merits of the suggestion.

**Comment by petertseng** [comment]
> I'm told I can manually trigger a build at any time

I have further received the report that this is done by:

> I used the "trigger build" button in the upper right next to the word "more options" while viewing a past build on master.

**Comment by bdw429s** [comment]
> making PRs from a personal fork rather than on Exercism's copy 

From my understanding the build still runs "on the exercism repo" for a pull request, even if the pull is sourcing from a branch in a fork.  See this build as an example:

https://travis-ci.org/exercism/coldfusion/jobs/276405495

**Comment by petertseng** [comment]
> From my understanding the build still runs "on the exercism repo" for a pull request, even if the pull is sourcing from a branch in a fork. See this build as an example:

That's fine with me. That's a PR build, not a branch build.

**Comment by bdw429s** [comment]
> That's a PR build, not a branch build.

Yes, but I believe the original impetus was that the Exercism organization in general had limited bandwidth for the total number of builds happening every day regardless of their type.   Whether PRs are made from the base repo or a fork seems to still "use" a build slot up.

**Comment by petertseng** [comment]
> Whether PRs are made from the base repo or a fork seems to still "use" a build slot up.

This is true, but I think that we want to build PRs. We just want to build them once, not twice (as in https://github.com/exercism/haskell/pull/580 - I see "2 checks passed", "continuous-integration/travis-ci/pr The Travis CI build passed [Details](https://travis-ci.org/exercism/haskell/builds/256173265)", and "continuous-integration/travis-ci/push The Travis CI build passed [Details](https://travis-ci.org/exercism/haskell/builds/256173141)")

**Comment by kytrinyx** [comment]
> Whether PRs are made from the base repo or a fork seems to still "use" a build slot up.

This is correct, and desirable. What we were seeing was that we would create a branch on the repo (not a fork), push to the branch (the branch gets built), create a PR (a PR gets built). We were trying to eliminate the first build.

I don't want people to have to do manual work, but I also don't want to have twice the number of builds. It seems unnecessary to make everyone create forks.

I would like to suggest the following settings.

* master cannot be pushed to directly
* before they can be merged, all pull requests must
  * have a passing build
  * be up-to-date with master

This is similar to my first suggestion, but I've removed the bit about "at least one approval" because we don't have enough maintainers to make that possible.

Another option for master is to do what @Stargator suggested in the Dart track and add `branches: only: master` to the travis config.

However, I really don't want us to be pushing to master, both for the sake of visibility (notifications happen on PRs not on pushes to master) and for the sake of safety (v2 updates the website based on master automatically and immediately. The site would break even before a build completes, if we get something wrong).

**Comment by petertseng** [comment]
1. Based on my understanding of the properties Exercism wishes its CI to have, I think I cannot stand behind my suggestion of turning "Build branch updates" on, unfortunately.
2. Regardless of whether that's true, I still suggest that development branches be made on forks, not on Exercism's copy.

Readers who only wanted to see that summary can stop reading; the below only expands on the above two points.

---

My understanding of the properties we desire:

* The most important, and critical, is **Safety**. Before a given commit is used by the website, it needs to have a passing build.
* Also important, but not critical, is **At-most-once**. We'd like to avoid building commits twice, which is especially important when PRs are simultaneously made to all language tracks.

The suggestion:

> * master cannot be pushed to directly
> * before they can be merged, all pull requests must
>   * have a passing build
>   * be up-to-date with master

maintains both properties. I strongly dislike the "be up-to-date with master" setting, but I have no alternative that maintains the desired properties.

My suggestion of turning "Build branch updates" on for all branches has no effect on Safety, but interferes with At-most-once because everything will get built twice and maybe thrice.

1. If a branch is made on Exercism's copy of the repo, the branch is built.
2. The PR is built before it can be merged.
3. After it gets merged to master, master is built.

The second build is what we desire in all cases, but the first and third are not.

The suggestion of https://github.com/exercism/dart/pull/35#issuecomment-329393417 always eliminates the first build, but never the third.

At this point the only disadvantage I have left to offer of leaving "Build branch updates" off is that any Travis CI badge (The ones that say "Build: passing", see e.g. https://github.com/exercism/ruby which uses https://travis-ci.org/exercism/ruby.svg?branch=master) are relatively useless since we will not have any branch with up-to-date builds for that image to use. Perhaps the issue can be remedied by using https://docs.travis-ci.com/user/cron-jobs/ to build master periodically. I will trial this immediately.

The only alternatives I have to offer to preserve Safety:

* I wish the suggestion of https://github.com/exercism/discussions/issues/174#issuecomment-317535363 (a published branch) would work, but in an automated fashion. If Travis-CI would, upon a passing build on master, push the commit that passed to a branch (let's say it's called the `green` branch), then the website can use the `green` branch instead of the `master` branch, and no manual work is required. Unfortunately, I do not see Travis-CI offer such an option.
* If the website would inspect the build status of each commit on master, and only take the most recent one for which the build is green (rather than the most recent one, unqualified), that would do, but increases complexity. I can't recommend that the website does this (but y'all can if y'all want...).

---

On using forks versus Exercism's copy of the repo:

> It seems unnecessary to make everyone create forks.

Well, every would-be contributor who doesn't have write permissions to the repo must create a fork anyway.

In either case, I still think what I say in https://github.com/exercism/discussions/issues/174#issuecomment-317504971 applies:

>    * When a repo is forked, all branches are copied. If branches are made on Exercism's copy, we foist branches on forkers unwittingly. Mitigation: Forker deletes the branch after forking.
>    * By default (unless the fetcher uses `-t` flag), git remotes are set up to fetch all branches. So if branches are made on Exercism's copy, again we foist branches on fetchers unwittingly. Mitigation: use `-t` flag.

I don't have any force behind those bullet points or any strong principles on why they're a good idea; just vague feelings of "if there are branches on a repo that people might clone, they should only be branches that people would benefit from having", and I think a lot of the branches we've made are those that people do not benefit from having.

**Comment by Stargator** [comment]
As a contributor on GitHub, I'm used to forking repos and keeping up work.

**Comment by kytrinyx** [comment]
> My understanding of the properties we desire:
> * The most important, and critical, is **Safety**. [...]
> * Also important, but not critical, is **At-most-once** [...]

@petertseng thank you, this is an excellent summary.

> I strongly dislike the "be up-to-date with master" setting

I'd like to understand this stance better. What do you dislike about it?

> When a repo is forked, all branches are copied. If branches are made on Exercism's copy, we foist branches on forkers unwittingly.

I understand the technicality of it, however I'm not certain I understand why these branches are a burden. I do my best to prune and keep unnecessary/dead/finished branches to a minimum. If we had hundreds or (as I've sometimes seen, thousands, many of which are years old) then yes—definitely a problem. But if there are a handful of branches, I don't understand what problem they're causing. Would you please help me see your point of view?

> Well, every would-be contributor who doesn't have write permissions to the repo must create a fork anyway.

Yes, that's completely fair. That said, most contributors only need to fork and clone one or two or at most a small handful of repositories. I think that if I just needed to create one or two repositories I wouldn't mind, but I need to have a fork of 60 different repositories on my personal account. I did this for a while, and invariably I would miss something, even when I scripted things as much as possible. Every time I bootstrap a new repository, I must also fork it to my personal account. I need to make sure to keep master on my local copies up to date with 60 different upstream repositories, and also update my 60 forks. In my case it adds a not-insignificant additional burden in order to do janitorial work that I most often wish I didn't have to do in the first place.

**Comment by petertseng** [comment]
> > I strongly dislike the "be up-to-date with master" setting
> 
> I'd like to understand this stance better. What do you dislike about it?

Consider the case when I have N PRs simultaneously in flight.

Without "be up-to-date with master":

* As soon as the build passes for each PR, it can be merged.
* Dangerous (violates Safety) if multiple PRs pass CI individually but fail CI when merged.

With "be up-to-date with master":

* Choice 1:
  * Merge the first PR, rebase[1] the second, wait for CI to run, merge the second, rebase[1] the third, wait for CI to run...
  * Turned a parallel operation into a serial operation.
* Choice 2:
  * Octomerge all PRs simultaneously.
  * Incurs the cost of one additional CI build (the build that ensures the octomerge result is good), rather than N.
  * I highly prefer over choice 1.
  * Examples of when this has been done in Exercism in the past:
    *  https://github.com/exercism/haskell/commit/381d33942c62bcad6dbbba56a0ae373e1b2f69c5
    * 
https://github.com/exercism/haskell/commit/a142b266120bd2e50354991a994346bb57a03687

[1]: It does not matter whether we rebase on master, or use GitHub's "Update from master" (merges master into the branch) with the intent to squash later; the parallel -> serial still applies.

As you can see, although it is **necessary for Safety**, it does slow things down. As long as I can still octomerge so that I'm only slowed down by O(1) instead of O(N), I accept the slowdown for the sake of Safety. If there is any setting that prevents my ability to octomerge, I will not be able to accept the slowdown.

(You may look at https://github.com/exercism/discussions/issues/174#issuecomment-317269107 for a past discussion, but I have put the relevant information here as well, so you do not need to)

---

> > When a repo is forked, all branches are copied. If branches are made on Exercism's copy, we foist branches on forkers unwittingly.
> 
> I understand the technicality of it, however I'm not certain I understand why these branches are a burden.

Me neither. Are they?

I can speak for myself. I don't like to keep old branches around, and maybe I don't like to see other people old branches around. Let's say we do development on exercism's branch B. Contributor C forks the repo during that time, and now they have branch B. We merge branch B and then delete it. Ah, but Contributor C still has branch B on C's fork, and there is no way to delete that unless C explicitly takes action.

So, is that a problem? I know such a thing bugs me personally, but for the purposes of this discussion maybe it's only a problem if Contributor C cares about it. We haven't heard anyone complain, have we?

> I need to make sure to keep master on my local copies up to date with 60 different upstream repositories, and also update my 60 forks.

You would have to do this no matter whether your local copy's `origin` is a personal fork or Exercism's copy, so on *this* point it seems to me it makes no difference whether you fork.

> I need to have a fork of 60 different repositories on my personal account. I did this for a while, and invariably I would miss something, even when I scripted things as much as possible. Every time I bootstrap a new repository, I must also fork it to my personal account

On this point, it does make a difference. (I have no additional comments to add but am just pointing this out to contrast with the above point)

> In my case it adds a not-insignificant additional burden in order to do janitorial work that I most often wish I didn't have to do in the first place.

I wondered if it would be too sardonic to say "then just don't do it", but I know that not doing it is not an option when the change blocks a configlet release or a website change, so I have no alternative to offer.

So, I really don't have any force behind the suggestion, and I fear my reasoning just boils down to "it bugs me but I can't explain why". Making branches on Exercism's repo bugs me at about a level of 4/10, so if making forks bugs you at any level >= 4, I take your word for it.

**Comment by petertseng** [comment]
EBWODP:

Correction: I claimed that for "and also update my 60 forks." it doesn't matter whether you fork, but obviously it does. Rather, the point to make is that from a local point of view, the operations performed are the same, and it doesn't matter whether the fork's master branch is up to date or not.

**Comment by petertseng** [comment]
EBWODP:

Thus, I am adding the following to my comment:

> and also update my 60 forks.

I personally don't think it's necessary to keep the *master* branch of the fork (as it appears on GitHub) up to date. It's necessary to keep it up to date *locally*, of course. I set up my forks so that the master branch (and only the master branch) pulls from Exercism's copy.

**Comment by petertseng** [comment]
EBWODP:

> I set up my forks

To avoid any misconception that I'm doing something with the repo as it appears on GitHub, I'm saying "I set up my local repos" instead so that it's known I'm referring to the repo that exists on my computer.

**Comment by kytrinyx** [comment]
> I wondered if it would be too sardonic to say "then just don't do it", but I know that not doing it is not an option when the change blocks a configlet release or a website change

It's not an option. I'm already a huge bottleneck. I'm trying my best to make it so that I am not, but it's a long, long road.

> I fear my reasoning just boils down to "it bugs me but I can't explain why".

That's completely fair.

> Making branches on Exercism's repo bugs me at about a level of 4/10, so if making forks bugs you at any level >= 4, I take your word for it.

I'll think on it some more. I really appreciate you taking the time to explore the nuances in this.

**Comment by petertseng** [comment]
I am trying to see if someone (well, someone on the internet) has written anything on the subject matter, but I have not yet been able to find anything.

I may have inherited my attitude from someone on my team who says "I want the main repo's branches to be pristine so people looking at it don't get confused by the branch list", but I suppose we don't have so many branches as to make that a concern.

I asked about that and heard in response that a certain project really wanted to ensure that their main repo has as few refs as possible so that it wouldn't be so slow to clone. Again, I don't think we have that many branches that it's a concern.

It seems that these concerns are useful in larger repos, but not as important here. So I guess that's why it bugs me without me being able to explain why. Since there's less mental overhead for me if I keep the same workflow for all the projects I work on, it's why I continue to use forks for Exercism, but the same doesn't necessarily apply to anyone else.

**Comment by Stargator** [comment]
> When a repo is forked, all branches are copied. If branches are made on Exercism's copy, we foist branches on forkers unwittingly.

Here's the thing, GitHub won't let you merge in changes if there are conflicts with the PR and master. The setting to be "up to date with master" is meant to avoid conflicts. But any PR reviewer should see the notification by GitHub that there's a conflict.

Given then, unless git detects a conflict I think it is fine to work without the "up to date with master" setting.

My team has been using GitHub for just two years. At some point, we started using the setting, then switched it off because GitHub prevents PR merges (through GitHub, not command-line).

So maybe consider that.

**Comment by petertseng** [comment]
> Here's the thing, GitHub won't let you merge in changes if there are conflicts with the PR and master.

I agree that this statement is true.

> The setting to be "up to date with master" is meant to avoid conflicts

I disagree that this statement is true... depending on the definition of "conflict". It doesn't do anything with regard to conflicts in the `git merge` sense, since you always have to resolve those no matter whether "up to date with master" setting is enabled. One thing the setting helps to avoid is the sort of... we'll call it logical conflict where two commits that branched off of master at the same point pass CI individually but fail CI when merged together.

**Comment by kytrinyx** [comment]
> One thing the setting helps to avoid is the sort of... we'll call it logical conflict where two commits that branched off of master at the same point pass CI individually but fail CI when merged together.

Yes, this is exactly it. We've run into this problem on several occasions, where the conflict is conceptual, not an actual line/merge conflict.

**Comment by kytrinyx** [comment]
> It seems that these concerns are useful in larger repos, but not as important here. 

Thank you for elaborating, @petertseng.

In this context, where the repos are quite small and the branches are low in overhead both mentally (looking at the list of branches and seeing what's going on) and resource-wise (in terms of cloning), I'm going to go ahead and make the call that maintainers _can_ (but are not forced to of course) work on branches on the main repository.

@petertseng -- the proposed settings would still allow octomerge, correct?

**Comment by petertseng** [comment]
> the proposed settings would still allow octomerge, correct?

As far as I can tell, yes. I have tested this on a repo where I changed the settings to those proposed.

**Comment by petertseng** [comment]
Here is a potential concern with "require branches to be up-to-date with master". The potential impact increases as the repo has more simultaneous PRs in flight:

I wonder if this will tempt some people to use the "Update branch" button, making a merge commit, and then also use "Merge pull request" that makes another merge commit.

Again, this bugs me but I'm not sure if I should be bugged by it. The best explanation I can come up with is that I want at most one merge commit, because I think having two is redundant and I like to avoid redundancy when possible. I like one merge commit if the PR has multiple commits since it acts as a record of what PR the commits came from, but I don't really have a justification for two merge commits.

There are many ways that avoid doubling up on merge commits. So the concern is mitigated if we are aware of the below ways.

* Merger uses "Squash and Merge" button. This is only possible if the PR makes sense as a single commit.
* Merger uses "Rebase and Merge" button. The only thing I don't like about this approach is that as far as I can tell it is then no longer possible to tell what PR the commits came from if I don't have an internet connection. I don't know if that is an actual concern; I have not actually had to make use of this information without an internet connection, so it is possible that Rebase and Merge is the way to go if the PR must remain as multiple commits (Squash and Merge is thus not an option).
* Merger rebases the branch on master and pushes it to contributor's fork, and only then uses "Merge Pull Request", creating one merge commit. Not possible if contributor explicitly chose to disable that (I typically don't see people disable it).
* Well, one repo on which I think this concern may surface itself is problem-specifications. BUT, maybe we decide we do not need "Require branches to be up-to-date" for the problem-specifications repo, because the live site does not depend on it (right?)

**Comment by kytrinyx** [comment]
> Again, this bugs me but I'm not sure if I should be bugged by it.

This bugs me too, but I've decided to live with it, because it gives me safety (in other words, it's not truly redundant, because it provides safety, but it feels redundant, because it has extra merge commits).

> one repo on which I think this concern may surface itself is problem-specifications. BUT, maybe we decide we do not need "Require branches to be up-to-date" for the problem-specifications repo, because the live site does not depend on it (right?)

Yes, that's correct. I think we do not need to make this a required setting for that repository.

**Comment by Stargator** [comment]
Frankly, I use Squash and Merge. A PR shouldn't be so big that the effort *needs* to be broken up into commits. If so, then the settings could be changed to allow whatever approach seems best at the time and then revert back.

**Comment by kytrinyx** [comment]
_We've imported this issue to the https://github.com/exercism/exercism.io repository._
