### ISSUE TITLE
Testimonials for tracks—has Exercism been useful to you?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#176]
People say really nice things about Exercism a lot, and I've been dismally bad at saving these things up to use later.

One of the things that would be absolutely lovely is to have some quotes about each different track from people who have enjoyed the process, learned things, etc.

So. If you have nice things to say about any of the tracks (or if you see/overhear people saying nice things), would you drop those nice things here? If we get enough of these we could use them on the new site.

**Comment by budmc29** [comment]
Recently I made a resolution to spend more time doing programming challenges and the first thing that came to my mind was Exercism after being impressed by the first challenge I did in December 2015

> Exercism is a great website where I was able to have some very interesting challenges.
> What I like about it is that I am able to solve the challenges in a TDD way working in a environment that I am familiar (my own PC not a browser IDE) and the cherry on the top of the cake is that I have access to code reviews.
> The reviews are incredibly helpful because they help me see things that I missed, learn about new ways and sometimes interesting discussions that can add a fun twist to maybe a simple problem.

There are of course many other great things about it, like seeing how 10 people might come with 10 different solution to a problem, no to mention the community which is very helpful.

To end my message with my opinion on Nextercism, since I am a programmer I don't mind the site or the UI/UX since the selling point for me since I started was the curriculum and that I can run things on my machine from the CLI, but I do understand the need for it.

Keep up the great work, I am curios to see how every thing will turn up.

**Comment by ErikSchierboom** [comment]
To me, the standout track has been the Haskell track. With only a very limited grasp of functional programming, the frequent and insightful comments I received were invaluable in getting to know the language.

**Comment by kytrinyx** [comment]
@ErikSchierboom I've heard this from more than one person!

**Comment by kytrinyx** [comment]
> seeing how 10 people might come with 10 different solution to a problem

@budmc29 ✨ this is one of my favorite parts of Exercism. I learn so much from different people solving things in different ways.

**Comment by ceddlyburge** [comment]
The c# markdown problem is my favourite, it is sufficiently complex to be interesting, and is similar to a lot of the code that I see. Writing good quality code from scratch is generally easier than refactoring existing bad quality code to make it good.

**Comment by m1kal** [comment]
I loved the Ruby track (it is the only one I have finished so far). Solving over 80 different problems seems one of the most exciting ways to learn a language one barely knows. Improving my own solutions for readability and beauty rather than just passing the tests and performance taught me a little about Ruby and programming in general. I also liked comparing my solution to other ones - I could see the problem from other points of view.

**Comment by JamesAnthonyLow** [comment]
I'm a newcomer to exercism.io.  I've been working as a systems engineer for about a year and I've been putting off learning assembly properly (I don't have a degree).  I've been doing the MIPS track and not only do I feel like I am really increasing my level of insight into the inner workings of the machine, I'm having a ton of fun doing it.  Thank you so much to everyone who is putting work into this.

**Comment by ozan** [comment]
Glad to hear it @JamesAnthonyLow ! You've inspired me to put a bit more love into the track :)

**Comment by JamesAnthonyLow** [comment]
Awesome 👍

**Comment by nickdelany** [comment]
I'm working through the F# and Python tracks at the moment. Really like the ability to look at other people's solutions. I've had some helpful comments from others too.

**Comment by aklap** [comment]
Exercism has been really wonderful for me. It was the first time that I ever contributed to an open source project (it's a nice feeling knowing that when people use Exercism I may have helped them in some way), how I learned JavaScript, and how I learned about testing and TDD. I learned so much by osmosis just from reading: all the submissions and all the code while running the site locally and trying to understand how Exercism works. 

Last week, someone in a Slack I'm in asked for help with debugging one of their JavaScript submissions. I was going to just make a comment on it in the channel, but realized two things: how much I had learned in the past year, enough to help someone, and how easy to use and conducive the submission page is for learning and commenting on code for that purpose. So it definitely came full circle in a way. I'm looking forward to the next iteration of Exercism! Thanks Katrina & everyone that has contributed.

**Comment by kytrinyx** [comment]
@aklap So much 💕! That's one helluva progression you've had in the past year!

**Comment by tleen** [comment]
Exercism is fantastic, it saved my career. You get to a point eventually where

**Comment by robphoenix** [comment]
I was originally employed as a network engineer at a large UK telecommunications company, my first job after changing careers in my late thirties. I had started learning a little Python prior to this, due to the hype of software defined networking. This quickly led to me becoming the *scripting guy* at work, and eventually the lone software engineer tasked with building automation tools. I first heard of Exercism through the [Changelog podcast](https://changelog.com/podcast/108) and it became instrumental in making me a programmer.
I started with the Python track which helped me to better understand the language's syntax and data structures. The track also improved my ability to understand a problem and form questions around it so that I was able to find or learn what I needed to in order to find a solution. 
I have spent time with the Clojure, Elixir & Go tracks and all have been incredibly beneficial, providing self-contained finite problems with which to learn the language. The Go language track has been wonderful in introducing me to the language, what idiomatic code is, and the many different ways in which one can solve a problem. 
Just as importantly, for someone who is not part of a software team, the opportunity to get feedback, to learn how to improve and to learn how to read others code and engage in a conversation about it, has been invaluable.
And lastly [my first real PR](https://github.com/exercism/elixir/pull/64) was for Exercism, a gateway drug to the world of open source. It's not an understatement to say Exercism has had a profoundly positive impact on my career and life. Thankyou.

**Comment by aklap** [comment]
Yes @kytrinyx , I feel like I really grew after using Exercism; something about the repetition of running tests and reading errors just really helped it all click for me. 

I know this is for testimonials for specific tracks, (and I feel like I owe a lot to the JS and Ecmascript tracks), but there's so much value in reading the docs, setting up a dev environment and running Exercism locally and just poking around the files, reading them and just trying to figure out how the site works. It was like going from understanding the basics about coding via the exercises to then seeing how we can apply these concepts in a practical app when contributing that was so valuable. I hadn't read or written any Ruby in a year+ and just reading the code for the site was a great refresher. So even though it's not a track, the fact that Exercism is open source is a great resource for learning.

**Comment by kytrinyx** [comment]
Thank you for all the lovely testimonials! The new site has launched (including testimonials). If anyone wants to say more nice things, please open an issue with it in http://github.com/exercism/exercism.io/issues ❤️ 💛 💚 💙 💜 🖤
