### ISSUE TITLE
Track health, mentors & maintainers

### ISSUE THREAD

**Issue by tleen** [exercism/discussions#191]
This issue will serve to consolidate the discussions concerning track mentors, track maintainers and overall track health/lifecycle going into nextercism.

**TL;DR**

Maintainers and mentors will both be vital for overall track-health in nextercism. How do we ensure tracks have enough of both? How do we categorize track health? What to do about tracks that need help?

## Mentors / Maintainers

The move to explicit mentoring in nextercism has brought up a good number of issues concerning implementation of mentorship. These include:

- [mentor approval requirement blocks progress](https://github.com/exercism/v2-feedback/issues/36)
- [how mentorship applies to existing v1 solutions in nextercism](https://github.com/exercism/discussions/issues/189)

While these have been tackled as separate issues we are really looking at a single core issue: track health and how it relates to the maintainers/mentors. Mentors add a new twist to track health as they will be an important resource for users in nextercism.

**Maintainers** will be the @exercism/track-maintainers: those responsible for keeping (their) tracks up-to-date and resolving issues. More than one maintainer is beneficial for a track for a number of [reasons](https://github.com/exercism/discussions/issues/174).

**Mentors** are a role new for nextercism: individuals with permissions to review and approve exercise solutions on a per-track basis, unlocking core exercises for an individual's progress. Mentors may also end up as the best resource for track refinement feedback as they will have a unique visibility into spots where users are finding common roadblocks in their progress. Mentorship of a track will also be a good way to recruit maintainers, they will most likely be language enthusiasts and (through mentorship) become familiar enough with tracks to contribute in other ways. It therefore also likely many people will end up being *mentainers*: performing both activities for a track or tracks.

One of the big issues with nextercism is going to be figuring out [how to recruit track mentors](https://github.com/exercism/docs/blob/master/language-tracks/launch/finding-mentors.md). If a busy track ends up with only mentainers, there could be a risk of [burnout](https://github.com/exercism/discussions/issues/36). It may end up being too much to deal with issues on a track and have to review exercise submission on the track to keep users moving forward. Ideally, if we can get mentors we will eventually get more maintainers as well. Recruiting mentors, then, should be a top priority for each track.

## Track Health

Where maintainers were a crucial indicator of track health, we now have to watch for mentors as well. A track without mentors could cause users to abandon it should their [progress be blocked](https://github.com/exercism/v2-feedback/issues/36). We need to discuss what to do about tracks that lack maintainers/mentors as well as tracks that have [not progressed](https://github.com/exercism/coldfusion) into significant implementation. Roughly tracks exist as such:

### Categorizing tracks based on open source activity

**The Whim**

Some tracks get requested, and then don't get *any* meaningful activity. Nobody adds any exercises, sets up CI, or adds documentation (end-user or contributor). Nobody responds to pings.

These, perhaps, we should delete after a set amount of time with no meaningful activity, and we should have a way to communicate this up front. Maybe also communicate why this is so (it takes actual real work on our part to keep these alive. Invisible, tedious work).

**The Fizzle**

Then there are some where there is a flurry of activity, but not enough to even get it launched. The bar for launching has historically been very, very low. I think the solution to this is a combination of raising the bar, and actively looking for a small team of interested folks to take responsibility for getting the track into shape and launched.

**The Orphan**

There are a bunch of tracks that had enough activity to launch at some point. Then the maintainer(s) drifted off and the track is now unmonitored.

### Categorizing tracks based on site activity

**No Interest**

If people are not doing any of the exercises, perhaps we could *archive* the track. Not show it on the site, not even pretend to maintain it.

**Low Interest**

If there is some (but not a lot of) interest, perhaps we should put the track on life support. In terms of maintainers we could have a group of "guardians" or "unmaintainers" who basically accept pull requests without doing much in terms of review-just make sure it passes the build. For mentors, it's also tricky. If despite the low interest we don't have anyone giving feedback, we need to decide what to do.

There are discussions ongoing about how to best accommodate the "power user" [use case](https://github.com/exercism/v2-feedback/issues/36) for going through a track. Perhaps we could put these tracks into "power mode only" or whatever that behavior would be, so that people are not blocked by not getting feedback, but that they still could get feedback if mentors are actually available.

**Plenty of Interest**

If there is a lot of interest and activity on the site but too few mentors, *we would have to actively pursue mentors*. We would need a structured plan for how that outreach should happen, what sort of places we can find relevant people, and what the messaging is. Some ideas—are there active language communities? Does the programming language have a community manager who is invested in developing the resources and community interest for the language? Can we recruit from among the people who are already active on Exercism? Are there meetups? Forums? IRC channels? Conferences? Bootcamps that use this language to teach? Universities that teach this language? *We need ideas around all of this.* V2 is going to require us to do a lot of work to lower the barrier to giving feedback, so I think this work might be in line with the work we have to do anyway to support the really active tracks on the site, even if we already have people giving feedback. It's going to be a lot of work, though, and it's only worth doing that work if there's significant interest on the site.

(Much of the track health info above via @kytrinyx with some minor modifications :smile:)

There are already some good ideas floating out here about how to handle new tracks. @Insti and @NobbZ [have some](https://github.com/exercism/discussions/issues/143#issuecomment-317678216) which are a combination of raising the bar for a new track and setting up a conceptual "nursery" for new tracks. It may make sense to have a separate "sick bay" for tracks that are abandoned or in critically unmaintained status.

Mostly this issue is hoping to get a good amount of consolidated discussion about track health, the mentors/maintainers and how to recruit more of the latter.

### Related Issues

[How do we ensure that tracks are not orphaned?](https://github.com/exercism/discussions/issues/3)
[About burnout and avoiding maintainer guilt](https://github.com/exercism/discussions/issues/36)
[Explicitly look for new contributors for language tracks](https://github.com/exercism/discussions/issues/85)
[What do we do about unmaintained tracks?](https://github.com/exercism/discussions/issues/102)
[At what point should requested tracks be deleted if they don't get implemented?](https://github.com/exercism/discussions/issues/143)
[We need a buddy-system for launching new language tracks](https://github.com/exercism/discussions/issues/152)

**Comment by tleen** [comment]
For starters it looks like a lot of issues regarding track health go away if a track has sufficient mentors and maintainers. So it looks like part of track maintenance is ensuring a decent number of mentors, probably related to overall submission level in nextercism. Hard to tell what a *decent number* of mentors would be for any given track. You can see a situation where one high-frequency mentor could handle the same number of submissions that two or three lower-frequency ones.

It does seem to make sense that @exercism/track-maintainers are the best individuals to coordinate mentor outreach. It is probably worth *looking through track traffic now* to see who frequently comments on other's exercises as they may be good candidates for mentorship. A safe assumption would be that track maintainers are aware of other commonly used resources for their track languages: forums, reddits, conferences, mailing lists, local enthusiast meetups.... Unfortunately that would represent another thing for track maintainers to put on their plate.

If `track health == (mentors + maintainers)`  **where are some good places to find mentors?**

Nextercism will also have to incorporate some policy for tracks with no mentors, or inactive ones. If progress through a track is contingent on approval by a mentor, at what point is a track considered un-mentored? No approvals in a day? In a few days? or would it be 10 submissions awaiting approval, 100?

Should a track with no mentors be considered an abandoned track that users cannot progress in or should we fallback to the v1 auto-mentor (tests pass, you move on)?

**Comment by kytrinyx** [comment]
Thank you so much, @tleen, for taking the lead on this conversation.

> Hard to tell what a decent number of mentors would be for any given track. You can see a situation where one high-frequency mentor could handle the same number of submissions that two or three lower-frequency ones.

Yeah, this is likely to vary not only by the activity on the track (see https://github.com/exercism/v2-feedback/blob/master/mentors/v1-average-activity-by-track-per-day-20170815.txt for some recent numbers), but also by how active the mentors themselves are and how familiar the mentors are with the exercises.

I wrote a "code smell lab" for the Go Leap exercise which covers most of what I've ever seen come up in that exercise. This has proven to be a useful tool for helping more mentors to be familiar with the types of issues that come up, and the types of things you might point out or recommend.

[go-leap-codesmell-lab.pdf](https://github.com/exercism/discussions/files/1288388/go-leap-codesmell-lab.pdf)

I did something similar, but in a different format for the Bob exercise in Ruby, producing a conference talk about it ([Overkill](http://www.kytrinyx.com/talks/overkill/)).

Once a mentor has internalized the breadth of typical issues in the Go Leap exercise (or the Bob exercise in Ruby), and has some saved snippets and links to resources, then they can often whip through 5-10 solutions in just a few minutes.

I could see us make a whole project around producing this sort of code smell lab for every exercise on Exercism. We have 4 years worth of submissions and conversations about the code. It would take coordination, and probably some good tooling to make it easy to sort through all the noise and categorize things, but it would likely be a hugely valuable resource for helping new mentors be effective.

> It does seem to make sense that exercism/track-maintainers are the best individuals to coordinate mentor outreach.

I think that track maintainers probably have a good idea of where people hang out and good insights into where to find resources, but I don't think we should add this burden to their plates.

I believe that it would be very healthy to have people whose sole responsibility it is to focus on mentors. It's a very different sort of task than other tasks that fall under track maintenance, and it's a _huge_ task. I also think that a lot of people who enjoy maintaining tracks would probably not enjoy mentor outreach so much, and vice versa.

At work I am part of a "developer marketing" team, and we structure all of our work in the following way:

- **Support** - helping developers when they get stuck, troubleshooting, responding to questions and support requests.
- **Content** - as we do support work, we start seeing where the friction is, and we start noticing patterns. We produce canned replies, blog posts, tutorials, case studies, screencasts, conference talks, etc to address the things that come up the most often.
- **Outreach** - going to (and often speaking at) meetups, conferences, etc. Hanging out in forums, being a part of the community.
- **Operations** - start automating the things that are repeatable, formalize processes to reduce friction.
- **Programs** - once we start seeing the big picture, turn all of this stuff into an actual product with a name and a website. Now it's well-enough defined that we can typically hire people to focus purely on the program.

Each step builds on the previous step. Everyone typically does everything (especially support, because this is the most important place where we understand what the work we need to do is), but not all at once, and some people gravitate more naturally to certain things. I tend to focus on operations and content more than outreach and programs, for example.

What I imagine with the mentors is that we should have people who are focused solely on supporting the mentors. Some people might be focused more on support, others more on outreach. As we see the friction and the great parts, we might have some people who produce content about mentorship at Exercism, which can help draw new mentors in. All of this work will feed back into the product, and we will find ways of improving the mentorship part of the website. As we start seeing the patterns we can automate certain things. And finally, when everything starts rolling and we see the bigger picture, we might end up with a well-designed mentor program with a clearly structured onboarding process for new mentors, canned presentations that anyone could take to a local meetup, activity kits for workshops, etc etc. We can't design the program up front, it needs to grow out of all the previous steps, but seeing the shape of this whole process can help us in the earlier steps.

> It is probably worth looking through track traffic now to see who frequently comments on other's exercises as they may be good candidates for mentorship.

I think this is a great idea.

> Nextercism will also have to incorporate some policy for tracks with no mentors, or inactive ones.

Yeah, I don't know what the policy needs to be. I think that you should always get feedback within a day in a healthy track. We should have enough mentors that this is not a burden on anyone.

> Should a track with no mentors be considered an abandoned track that users cannot progress in[?]

My gut feeling is that we should never block people from doing the exercises. We're looking into designing a "power mode" where you're never blocked so that people who want to do a deep dive can do so. It won't be exactly the same as the v1 in that there is still some structure (core track, each core exercise unlocks optional exercises) but the basic idea is the same. I think that we should probably make insufficiently mentored tracks "power mode only", and make sure that people know this up front when joining a track.

An important thing to figure out would be how do we take a track that is power mode only, and add mentors. I'll be discussing this in depth with Thalamus, as this is an important user experience / user journey question.

**Comment by tleen** [comment]
@kytrinyx I think you are on the right track concerning a mentor's maintainer and mentor resources. The code smell stuff is good, I know that I am much better in reviewing an exercise after recently completing it or having done a few in a row. It helps me to remember the exercise and the pitfalls/expectations I had in solving it. Mentors will not necessarily need to have done the exercises in the track, just have enough capacity in the language to review solutions?

The code smells would probably be of three levels: global, a track (language) level, and then exercise level. For example:

* __Global__  "If see a bunch of if-elses, perhaps your language has a switch?"
* __Track__ (ex. Go) "If they don't need that variable use the _ to declare ignored-but-received"
* __Exercise__ (ex. Leap) "You are better off using a concise line of calculation to solve this than multiple discrete if statements"

There is a lot of fuzziness in here depending on track and exercise, but the general idea holds.

It may make sense to highlight the opportunity to become a mentor in both a power-user mode (they may make good mentors) and in whatever the mentorless track mode is (to advertise the need for mentors on that track).

While I agree that mentors are Yet Another Thing we do not want to add to a track maintainer's todo list, initially they still may be in the best position to find mentors within their own track users/contributors.

**Comment by kytrinyx** [comment]
Quick update on this:

We've been tackling mentors as a concern entirely separate from maintainers, even though several maintainers are also mentors, and several mentors have started maintaining.

I also have plans to focus specifically on reaching out to individual language communities for each track, to see if we can work with them to both improve the tracks, and help find more maintainers.

I'm going to go ahead and close this (with much regret!) since I'm not quite ready to start a full-blown effort to staff up all the tracks with adequate numbers of maintainers.

I do hope that we'll be able to tackle this as its own focused effort once we've sorted out more of the basics in the new site.

Thanks so much for taking the time to help think this through @tleen.
