### ISSUE TITLE
Implicit teams via GitHub organisations

### ISSUE THREAD

**Issue by RJacksonm1** [exercism/discussions#207]
I imagine the two barriers in front of users interacting and reviewing one another's solutions:

- The amount of submissions means there'll always be too much for a single user to go through. Maybe a user would spot check some recent submissions, but I imagine that's the exception instead of the norm.
- An uncertainty whether feedback will be valued. There's little motivation in providing feedback if there's a fear it will fall on deaf ears.

Teams strike me as a fantastic solution to these barriers as it personalises the solution feed to include peers a user already has a relationship with, and would significantly reduce the amount of peer solutions to review.

There remains a barrier for the adoption of teams, however:

- Teams need to be explicitly created, and
- Private teams need to manage members

A lot of teams already manage these steps via GitHub organisations, especially those who use GitHub as their primary code store.

It would make sense to hook into that existing data and use it to personalise user's feeds via implicit teams: If a user logs in and belongs to 'Acme Group', and there are 15 other 'Acme Group's members on the platform, implicit create an 'Acme Group's team & feed for those users.

What do you think? Does this make sense & seem technically feasible?

**Comment by kytrinyx** [comment]
Thanks so much for the suggestion!

It's certainly technically feasible; the GitHub API has support for everything we'd need to do in order to make this possible.

We're in the throws of redesigning most of the site, and teams are one of the next things we're going to dig into. I don't know where we're headed with this yet (and can't promise any particular outcome), but I'm adding this to the design questions list so that we can discuss it as part of the redesign effort.

**Comment by kytrinyx** [comment]
I'm tracking this on the "maybe someday" product list. Going to close it here, as it's not something we're planning on implementing in the near term.
