### ISSUE TITLE
Inconsistencies in unlocked_by values for tracks

### ISSUE THREAD

**Issue by nywilken** [exercism/discussions#211]
I'm currently reviewing a change to the underlying configlet tool https://github.com/exercism/configlet/pull/119/, which introduces verification for exercises that are unlocked_by others. In reading the documentation, https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md I see that exercises can only be unlocked_by core exercises. However, in checking a few tracks (e.g Go, JavaScript) I find that there are a number of exercises that are being unlocked by non core exercises. 

Has there been a change to the criteria for unlocked_by? If not, would it be safe to say that those tracks contain issues within their metadata and that I should ask the respective maintainers to update the tracks? 

Thanks in advance for the help.

**Comment by coriolinus** [comment]
I know of no changes to the formal specification. However, my inclination
is to say that the implementation _is_ the specification. The nonconforming
tracks were well-behaved, and after the configlet change, they no longer
are. Track maintainers will need to rectify the situation, but that's not a
reason to delay or change planned configlet improvements.

On Mar 4, 2018 14:50, "Wilken Rivera" <notifications@github.com> wrote:

I'm currently reviewing a change to the underlying configlet tool
exercism/configlet#119 <https://github.com/exercism/configlet/pull/119>,
which introduces verification for exercises that are unlocked_by others. In
reading the documentation, https://github.com/exercism/
docs/blob/master/language-tracks/configuration/exercises.md I see that
exercises can only be unlocked_by core exercises. However, in checking a
few tracks (e.g Go, JavaScript) I find that there are a number of exercises
that are being unlocked by non core exercises.

Has there been a change to the criteria for unlocked_by? If not, would it
be safe to say that those tracks contain issues within their metadata and
that I should ask the respective maintainers to update the tracks?

Thanks in advance for the help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/exercism/discussions/issues/211>, or mute the thread

**Comment by nywilken** [comment]
@coriolinus  thank you for the quick response.
