### ISSUE TITLE
Want to help mentor on the v2 site when we launch?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#214]
After a hiatus we're now working our way down a very concrete checklist for the v2 launch.

Mentoring is a huge part of the new site—we want to make sure that everyone who _wants_ support and feedback, gets the support they need. As part of that we're explicitly recruiting mentors.

If you're interested, please take a look at http://mentoring.exercism.io/

**Comment by lastgabs** [comment]
👋 I've just joined as a mentor ❤️ (thanks for having me!) and I remember reading docs/communication about ideas of having more concrete directions to mentors and how they should comment/interact with the exercises. Is this something that is ready? I want to start mentoring, but am having a hard time deciding on what needs to be done and how. Thanks!

**Comment by budmc29** [comment]
@lastgabs maybe you can help with making the onboarding experience for new mentors better.

You could get started on http://mentoring.exercism.io/ and provide insights of how do you find the experience, if it's straight forward enough, if there is enough information for anyone to get started etc.

We hope there will be many people that join mentoring that might not have all the inside information (and maybe they don't want to know more), and they want to get started right away.
For anyone familiar with all he processes everything is simple and makes sense, but that's because we are used to how things are around here.

But if that does not sound fun, then you can find more info about mentoring in this document: https://github.com/exercism/v2-feedback, and any issues you find can be raised in here: https://github.com/exercism/v2-feedback/issues

**Comment by lastgabs** [comment]
@budmc29 thanks for the quick reply! 
After I wrote the comment above I started second-guessing if I did actually get accepted as a mentor or if the mentor dashboard in v2 was open to everyone during the test version 😆I tried connecting but it's in maintenance mode (no cookies for me!). The reason why I'm wondering is because I filled out the form and a few days later when I logged into v2. exercism.io I saw the mentor dashboard so I assumed I got in, but I never received any notifications/email about being accepted.

I'll start making some contributions! Thanks for pointing me in the right direction 🎉

**Comment by iHiD** [comment]
@lastgabs You should have had a slack invite. If you didn't could you email me pls and I'll resend?

**Comment by lastgabs** [comment]
@iHiD just sent you an email to the email address in your Github profile. Thanks for checking this out for me ❤️

**Comment by kytrinyx** [comment]
Sounds like we got this sorted, thanks y'all!
