### ISSUE TITLE
Move from Heroku to Rackspace?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#23]
I'm in the middle of a huge amount of travel + preparing new talks for conferences + starting a new job, so this is a bit premature, but I figured we might as well start talking about it and figuring out what would be necessary.

Rackspace has an open source plan, which they've put Exercism on. That means that we have (more than) enough resources to run the site for free on Rackspace. Heroku doesn't really do open source sponsorship, and I've been running the site out of pocket on Heroku since the start. I mostly run some cron jobs, an extra dyno, and the postgresql addon. The postgresql costs $9/month at the current level, and we can use up to 10MM rows in the database. We're getting close to that limit (discussed in #15).

So. Tentatively, I'd like to figure out what it would take to move from Heroku to Rackspace.

Off the top of my head, this is what we're running (all on Heroku unless otherwise specified):

- exercism.io, the main site
- x.exercism.io, the API that delivers exercises (I will soon inline that back into the main site, it doesn't really help to have it as a separate service)
- rikki (runs as a daemon on a rackspace server)
- analysseur.exercism.io, the ruby static analysis service that rikki talks to
- a redis database (used to queue jobs for rikki. exercism.io enqueues them, rikki consumes them)
- a postgresql database
- various cron jobs

We currently do not send emails; if we start doing so, we will likely use a 3rd party service for that.

I've been extremely averse to moving to Rackspace for the very simple reason that I know virtually nothing about ops (seriously. [this](https://github.com/exercism/rikki/blob/master/bin/deploy) is how I deploy rikki. Don't judge.) I'm sure it would be fairly simple to get everything set up and moved, the problem is that if something goes wrong, I wouldn't know how to even begin troubleshooting, much less how to go about fixing it.

So... I think that if we ever do this, I would need a few people to be willing to mentor me—to be available to help me learn how to debug stuff when it blows up.

What have I missed?

/cc @cforain, @trevorbramble since both of you have indicated a certain willingness to help think about this :)

**Comment by cforain** [comment]
I think Rackspace is at least worth checking and testing. Also, I think that before trying third-party e-mailing services, we could try sending it from the application ourselves. With a bare-metal sendmail daemon (if we are only sending notifications), maybe we can work this out without raising the costs, by doing it ourselves. @bernardoamc and I had this experience with a Rails, and it was very positive.

**Comment by kytrinyx** [comment]
> With a bare-metal sendmail daemon (if we are only sending notifications), maybe we can work this out without raising the costs, by doing it ourselves.

Yeah, it would only be notifications, not any marketing stuff. That would be really nice, if we could do it without raising costs.

**Comment by TrevorBramble** [comment]
:wave: I am barely qualified but I won't let being a hobby-grade sysadmin stop me from sharing my own thoughts.

 * I don't know how heavy the cron job work is, so you may want that on another host, but maybe you can get away with scheduling all work for low-activity periods if you want it to co-habitate with the main service, or analysseur, or whatever.
 * You will probably want a cluster of Redis services, and likewise you'll want PostgreSQL to have replication and backups, obviously.
 * You _can_ start by using sendmail local to the application, but be prepared to shift that to a third party if your high volume/frequency mailings start being flagged as spam.

And now that I've though on it a bit I have to wonder ...would the wiser goal be finding sponsorships, to keep Exercism on Heroku and raise the data storage ceiling? If not, I'll see if i can round up some qualified sages to put together a plan and suggest resources.

**Comment by kytrinyx** [comment]
We can spin up several servers—the open source thing is "up to $2000 worth per month" or some insanely huge number like that.

> would the wiser goal be finding sponsorships, to keep Exercism on Heroku and raise the data storage ceiling? 

That sure would keep me feeling pretty peaceful! I talked to Heroku about sponsorships, but they don't really do that sort of thing. One of the developers there is going to ask around if there's a way that heroku could support Exercism with some extra resources, and so that may actually work out.

Other than that, I don't know who to ask about sponsorship—actual dollars is a different sort of sponsorship than "resources", which is what we currently have from various companies (free Bugsnag, free Rackspace, free Shopify, etc).

**Comment by mhelmetag** [comment]
A load balancer might be a somewhat safe way to "test" on Rackspace while keeping most of the users pointed to Heroku? We could then point both services to the same database.  Rackspace seems to have a load balancer service as well so that could help with implementation.

For the mailing, I'm all for the basic sendmail and action_mailer approach.

**Comment by cforain** [comment]
I think one other approach we can pursue, since we have a Rackspace sponsorship, is to migrate only our current bottleneck (the database, in our case).

> A load balancer might be a somewhat safe way to "test" on Rackspace while keeping most of the users pointed to Heroku? We could then point both services to the same database.

@mhelmetag I think this would introduce much complexity. It is surely doable, but I think that @kytrinyx goal here is to keep the infrastructure simple, in a way that even someone inexperienced like herself, can keep everything online.

Share your thoughts =]

**Comment by TrevorBramble** [comment]
> I think one other approach we can pursue, since we have a Rackspace sponsorship, is to migrate only our current bottleneck (the database, in our case).

@cforain :clap: Now that's smart! My only concern is latency between the application and database hosts, but that may not be an issue and can, I think, be worked around a bit if needed.

@kytrinyx, I'm still thinking about how ~~sponsors~~ funding might work. Talk more offline.

**Comment by kytrinyx** [comment]
> latency between the application and database hosts

We could test this, for sure. I think Heroku is on AWS, but I don't know which coast. I believe the Rackspace servers can be in several datacenters (rikki is running in Chicago right now).

> funding [...] Talk more offline.

OK, cool.

**Comment by cforain** [comment]
Well, I have worked on datacenters from Canada, US and Europe from Brazil, and latency is generally between 120 and 170ms. If both DCs are on North America, I doubt that it would go beyond 70 ms, which is more than enough for SQL queries. But I'm all for testing the performance, but I really think it won't be a problem.

I think that the biggest concerns with that approach are securing the server and hardening it against attacks and data theft.

**Comment by kytrinyx** [comment]
> I'm all for testing the performance, but I really think it won't be a problem.

Nice!

> I think that the biggest concerns with that approach are securing the server and hardening it against attacks and data theft.

Right, I suppose that if the servers aren't in the same data center it's going to be harder to open the db up to be accessed from just the right app on heroku. Hm.

**Comment by cforain** [comment]
> Right, I suppose that if the servers aren't in the same data center it's going to be harder to open the db up to be accessed from just the right app on heroku. Hm.

I don't have much experience with heroku per se, but theoretically, if postgres is running through a TCP stack (not socket) and the server has a valid IP (which is very likely), it would should be transparent for the app to connect.

Once again, unless Heroku have some specific firewall rule or something on the way, but I believe it is unlikely, since your app has to be able to connect to any ip in the world, because of its users.

**Comment by cforain** [comment]
I'm assuming the rackspace.com (173.203.44.122) is hosted in US (https://www.virustotal.com/en/ip-address/173.203.44.122/information/).

Pinging from one of my servers that are on Canada, we got a stable 25 ms RTT. I really think latency shouldn't be a problem, even if we used ActiveRecord.

**Comment by TrevorBramble** [comment]
@kytrinyx: Talked it over with @cwebberOps and he graciously offered to contribute his considerable expertise to the migration and ongoing support of Exercism. =^)

**Comment by cwebberOps** [comment]
I would love to help. I think it is just a matter of figuring out what needs to happen, etc.

**Comment by kytrinyx** [comment]
Holy smokes. Thank you!

Very pleased about latency probably being a non-issue.

So: I will get @cforain and cwebberOps a login to the rackspace thing and a database dump. That seems like the first step to actually figuring out if we can move the database to rackspace as a first step.

**Comment by cforain** [comment]
Excellent @kytrinyx . I have some questions though:

- How you manage your db right now? Create tables, indexes, users etc .
- Do you use migrations on exercism?
- Do you have separate test and development databases?
- How is your backup policy?

@cwebberOps I have a pretty open schedule as of right now, so I can do the initial heavy-lifting by myself and then we can work together from there. Share your thoughts =]

**Comment by kytrinyx** [comment]
Yeah, I have migrations on exercism. It uses the ActiveRecord::Migration stuff from Rails, even though we don't use rails.

I do have separate test and development databases. The tests clean up after themselves, so the test database should basically be empty unless you're in the middle of a test run. There's some seed data for development.

The backup policy at the moment is the default heroku postgresql thing: nightly backups. Not sure which timezone "night" we're talking about.

**Comment by kytrinyx** [comment]
@cwebberOps I've given @cforain a login on Rackspace, let me know if you need one as well.

**Comment by cforain** [comment]
Guys, I will probably get the server up today. As I said before, I am pretty confident there won't be any performance issues but rather, security implications. Here is a list of what things we can do to avoid such issues.

Things we should do:
 - Use private SSH keys
 - Disable direct root login, only few users on sudoers
 - Run postgres on a non-default port (5432)
 - If we use some db frontend like PGMyAdmin, we should ensure that php-fpm runs on a socket and that NGINX is as closed as possible. Also, use SSL. Is the current exercise SSL wildcard (so we can use it on any subdomain)? If not maybe we should decide if its worth to generate a new one. But since it is a private service, a self-signed is perfectly acceptable
 - Ensure pg_hba is correctly configured, so to only allow connections from desired hosts and with the best autentication possible
 - This is important: **ENSURE ANY RELEVANT SENSITIVE CONFIG FILES DOESN'T GET TO GITHUB**, like passwords and etc

Things we could do, but are more on the safe side for now:
  - Strong firewall rules
  - Limit kernel number of simultaneous TCP connections
  - Limit PG number of simultaneous connections
  - Study if there is a way to encrypt the connection between the servers, since I believe SQL queries will be flying plain-text between DCs. Have to check if that's the case.

If someone with more experience has some inputs, I would live to hear. Share your thoughts please.

**Comment by cforain** [comment]
Katrina, will you use some kind of gui (like phppgadmin) on the server?

**Comment by bernardoamc** [comment]
We can have native SSL: https://www.postgresql.org/docs/current/static/ssl-tcp.html

**Comment by cforain** [comment]
> We can have native SSL: https://www.postgresql.org/docs/current/static/ssl-tcp.html


I think this is perfect, as long as it is transparent (as in no significant connection nor configuration overhead) to the applications and services connecting to the database.

**Comment by kytrinyx** [comment]
> will you use some kind of gui (like phppgadmin) on the server?

@cforain no, I just use the command-line tool `psql`.

**Comment by kytrinyx** [comment]
Exercism doesn't currently have any SSL certificate. Even though they're not prohibitively expensive in theory, getting them working on Heroku is really, really expensive, as far as I was able to tell. So I never went down that route. We've basically relied on GitHub for login, so no passwords, and we don't expose people's email address anywhere. And the rest of the data is not particularly sensitive. I made the call that if someone gets your API key, the worst that they can do is submit solutions pretending that they're you, and if that happens we can (a) delete the solutions, and then (b) decide what to do next. I also implemented a private key / secret implementation that we can quickly switch to if we have to. But no SSL. Yet.

**Comment by cforain** [comment]
That is interesting. I deployed psql with SSL using a self-signed certificate, which kinda worked, but @bernardoamc and I are still having some issues. I really don't like the idea of plain-text data flying between datacenters, as non-sensitive as the data may seem. 

On a side note, I am having a little trouble to find a good definitive guide or documentation on connecting ActiveRecord to postgresql over SSL. So, I guess it's something worth looking up meanwhile. There are alternatives, such as tunneling postgresql through SSH, but I think it's kinda hacky, and believe that native SSL postgres is a much more elegant solution.

**Comment by kytrinyx** [comment]
I don't like the idea of having plain text data fly between the servers. We might very well ask for sensitive data in some places, even though I don't think that we expose it in the app.

>  I guess it's something worth looking up meanwhile. 

Yeah, interesting challenge.

**Comment by bernardoamc** [comment]
If we look at [ActiveRecord::ConnectionAdapters::PostgreSQLAdapter](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html) docs, we can see that default connection parameters of `libpq` can be set per environment variables. This will be excellent to define the SSL config. What I think we will need to set in the `Heroku` machine:

* PGSSLMODE
* PGSSLCERT
* PGSSLKEY
* PGSSLROOTCERT

These variables, are documented [here](https://www.postgresql.org/docs/current/static/libpq-envars.html).

**Comment by bernardoamc** [comment]
Just to serve as documentation, the connection would become something like:

`psql 'host=my_host port=my_postgres_port user=my_user sslmode=verify-full sslcert=my_client.crt sslkey=my_client.key sslrootcert=my_root.crt'`

**Comment by cforain** [comment]
@kytrinyx , now the we are beginning to study the possibility of having a more hands-on approach to the infrastructure of the project, there are some things we should consider in the long run.

For now, as we use PaaS (Heroku) for the application, and also for the database. We are studying the possibility to migrate the database because of PaaS limitations (in our case, 10M database rows).

But migrating to a self-managed infrastructure introduce some challenges, specially about the environment, such as tools and libs versions and this kind of stuff. Which is already our case, even with a "simple" database migration. As we will use SSL to encrypt the database connection, there will be different application configuration (see above), new files (self-signed certifications) and so on. Not only that, but we also have to ensure that everything will behave as expected when developing and testing, so there will be no "it worked on my machine" issues when changes go live.

So, what I'm suggesting is that, in a near future, maybe we should create a docker container file (or any other kind of virtualization) that mirrors as closely as possible the production environment (right now, the database, but also the other services in the future). That may seem like an overkill, but I think it provides many benefits:
 - This would streamline development and deployment. Since anyone contributing wouldn't even need to know how to install postgres, ruby, rails, nor any kind of dependencies. They would only need to run a container 
 - It would make updates more reliable, since once the production environment change in any way, we just need to update the dockerfile, and everyone developing would get a development environment that closely mirrors production
 - The dockerfile itself could be versioned, so theoretically, anyone could contribute to OS deployment or development environment issues, by issuing pull requests to the dockerfile
 - Having the deployment containerized would make any future migration much easier, as there are PaaS (such as Amazon EC2) that support container images right out of the box. So, for example, if we were to migrate the project to amazon in the future, we could use EC2 with our current dockerfile

Obviously, if we take that route, I would be willing to properly document every step to setup the development environment properly.

Please, share your thoughts =]

**Comment by kytrinyx** [comment]
+1 on a docker container. I know that @toolness was working on something here: https://github.com/exercism/exercism.io/pull/2760 but I don't know if this is compatible with what you're talking about (my limited knowledge of docker is asserting itself again).

Would you mind checking in with @toolness how the docker stuff is going? I don't know if he got stuck or just busy.

**Comment by toolness** [comment]
Hi! Actually I believe the docker PR is ready for review/merge? I hope I didn't miss something in the comments...

Going the Docker route for production would definitely be nice!!

**Comment by cforain** [comment]
Wow, I really thought you guys would think it to be an overkill. Glad you embraced the idea.
@toolness , thas a great effort, but how did you come up with the specification? It would be probably a good idea for us to deploy the project, and then we align that with the dockerfile, what do you think?

> Hi! Actually I believe the docker PR is ready for review/merge? I hope I didn't miss something in the comments...

I didn't quite get that. I believe it is a misplaced question mark, is it? If so, then you already have the proper production setup. Would you mind sharing more info on that? And is it OK to use this dockerfile as a base?

Also, the idea of running containers directly on prod is awesome. I will check it out: http://blog.rackspace.com/docker-with-the-rackspace-open-cloud/

Cheers =]

**Comment by kytrinyx** [comment]
>  I believe the docker PR is ready for review/merge

Aaah, in that case, it's just me losing track. So sorry! I'll merge that now, as a starting point for the dev thing, and as we figure out the production setup, we can update it.

**Comment by cwebberOps** [comment]
Sorry I haven't been more active in the discussion. Here are my general thoughts:
1. Running docker in prod scares the shit out of me. There is a lot that goes into the managing of containers etc that most people don't think about. With that said, if we can identify a sane way to run the infrastructure using containers, let's do it.
2. IMHO the biggest constrain lies in what Rackspace is providing. What they are willing to provide should dictate the mechanisms we use to build out the service. The fewer things (redis, postgres, etc) we need to run ourselves, the easier this will be to maintain, so let's take advantage of those things.
3. I would say, before we get too far, we should start with an architecture diagram. Once we have that, we tackle it piece by piece and modify it as we go. Just as it is good to do a read of the code around and related to what you are refactoring, an architecture diagram serves as an easy way to help us know what is going on and direct our efforts.

Couple of specific comments:
- @kytrinyx I would love a login to Rackspace, my email is cwebberops@gmail.com
- @cforain I love the 'Things we should do' post. My only disagreement is running postgres on a non-standard port. IMHO it doesn't help security enough to warrant not being able to look up the port number using google at 2am when things are down.
- I am going to take @kytrinyx info and try and get an architecture diagram put together, so we are all operating off the same map.

**Comment by cforain** [comment]
@cwebberOps Thanks for the input, here are my considerations:

1. I am yet to run containers heavily in production, but seems the current trend and, as listed above, it does have a lot of advantages. Even Rackspace (link above) made contributions to Docker so to facilitate running it on their infrastructure. I would love to hear more about your considerations, since you seem to have more experience in that area. What considerations are you talking about, besides maintaining the dockerfile and testing it? Please share more, if possible. I'm eager to hear =] 

Regardless, I guess we should have a development container, since would make it easier to set up the environment and make it more consistent. Thoughts?

2. I agree and disagree. Although PaaS has its conveniences, it is exactly the reason we are having all this "extra" work right now (Heroku artificial 10M rows limit). I'm not saying not to consider it further, it's just that it is a trade off between friction and freedom. So I think we should study the options more closely.  Also, I am yet check what are the PaaS options in Rackspace specifically, if any. If someone has some experience with it, please share.

3. I think this is an awesome initiative. Hit me up an e-mail if you need some help or an opinion, as I would love to be a part of it. And I agree with you about tackling each piece at a time. @kytrinyx did a god job modularizing the project, so theoretically we could migrate each piece as we see fit.

About the postgres ports, there are some automated attacks that are launched as soon as a CVE comes out that, sometimes, only targets the default service port. So, once again, it is a tradeoff we have to study. 

@cwebberOps if you get to work on the server, we should align our schedules with each other, so not to erase each other's work, and/or to share divide the tasks. Hit me with an e-mail in claudioforain@gmail.com to further discuss that. 

Cheers.

**Comment by kytrinyx** [comment]
> I would love a login to Rackspace

@cwebberOps I'll get that to you, probably this weekend.

**Comment by kytrinyx** [comment]
I received an email yesterday from someone I met who works at Heroku, and they've added a $500 credit to the exercism Heroku account. This means that I can upgrade the postgresql database, and it gives us several months of breathing room.

**Comment by lastgabs** [comment]
Hiho! Sorry to "butt into" this convo, @bernardoamc kindly pointed me here when I asked him questions about where to put an app and learn more about the whole pricing and how it works (newbie plx).

Reading this thread, I thought there are a couple of things that might be useful (or throw even more confusion into the game!):

- An alternative to Heroku: Rails Girls has a guide on putting rails apps online on different PaaS, one of which is called OpenShift. The interwebz seems to agree that it's one of the closest competitors of Heroku (they way it works, its setup etc.). They offer grants for open source projects & NPOs. https://www.openshift.com/grants/ 

- Heroku and SSL certificates: in June, Heroku released a beta flagged feature for providing free SSL certs for any apps that run on their paid dynos. I haven't been following it too closely to know how it's been working out, but might be worth it checking it out. Here's their blog post about it: https://devcenter.heroku.com/articles/ssl-beta

- Open source SSL certs: Let's Encrypt is the newest cool thing, free automated SSL certs. It's backed by several companies who want a safer free web for all. I don't know if it plays well with heroku, but I couldn't imagine there being discussions/questions about this online. Check them out: https://letsencrypt.org/ :) their support is awesome too, they are on top of their game all the time, constantly updating, etc. 

I'll go back to lurking around in the shadows again 👋 
Gabi

**Comment by kytrinyx** [comment]
Hey @lastgabs, thanks for adding this to the conversation. I'm really glad to hear that letsencrypt is doing a good job with support. They've come up in a couple of conversations, and I'd love to look into adding this to exercism.

**Comment by kytrinyx** [comment]
We have just received significant support from Heroku in the form of platform credits. This is going to let us upgrade the database, the redis instance, and use multiple dynos for the site itself.

Thank you so much to everyone who has helped figure out our various options and what it would take to pursue them! :heart: :heart: :heart:
