### ISSUE TITLE
Add stubs for all exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/discussions#238]
Some tracks currently have stub files for exercises. Other tracks only provide the test file. I propose making stubs a requirement on all exercises on all tracks. My reasons are:

- **Consistency:** A few drive for me is to make Exercism more consistent. This gives a better experience to the user and less confusion.
- **Helping beginners:** Creating a file is something which requires someone to Google. They have to work out correct file extensions, they have to work out correct basic syntax, etc. For C# a basic solution to two fer involves discovering and working out how to arrange all the following terms `public`, `static`, `using`, `class` and `string`. For Ruby it requires `module` or `class` and `def` - neither of which would necessarily be clear. Providing stubs reduces this hard learning curve. 
- **Reduction in support:** We get emailed a lot by people having no idea what to do to get started and a stub file would dramatically reduce that barrier.
- **Adding progression:** Each core exercise can have a reduced stub, until we just have a blank file with the correct filename. This gives a student a bit more work to do each time, but also means they have previous exercises to refer back to.
- **Auto-mentoring:** We need to be able to predict the file that someone will upload to be able to run static analysis on it. Having stubs enforces the file name of the solution, which reduces complexity for the auto-mentoring maintainers.

The three negatives I have heard to this proposal are:
- **Not teaching error messages:** If someone sees an error message of "file missing" or "require failed" and learn how to deal with it, then that is valuable. 
- **Learning how to create files:** Creating the file means you become familiar with the file extension etc.
- **Another job for maintainers:** All tracks will need to do this bit of housekeeping, and if we have progressively smaller stubs, then some thought needs to go into that.

My strong opinion is that the positives outway the negatives. I would also like to suggest adding the progression through reduced stubs into the Track Anatomy Project.

Previous discussion was [here](https://github.com/exercism/discussions/issues/114).

Have I missed any pros/cons? Does anyone have anything to add that I've not considered?

If people could :+1: and :-1: on this issue with their preference, I would appreciate it.

**Comment by wolf99** [comment]
The C track does something similar to what @Smarticles101 described for the Java track. Creating files is a key part of learning how to C good. The test file on the track make it evident what file/filename is required to be implemented.

I understand that this might be different in different languages. The fact that this difference exists should show that a blanket mandate that all language tracks provide files in a given way could reduce the value of some tracks.

An alternative might be to expose some metric on how many/much students struggle with this for any given track and thus handle it per track?

**Comment by ErikSchierboom** [comment]
> Creating files is a key part of learning how to C good. The test file on the track make it evident what file/filename is required to be implemented.

I don't see why the C track is different from other tracks to be honest. Creating a file is a key part of using _any_ programming language that uses source files (which most do). However, exercism aims to teach fluency in a _language_, not to know how to use an IDE or build system. I understand that creating files is an important skill to have, but I don't think it is something exercism should be teaching (or at least not for the vast majority of exercises, maybe only for the later exercises). An alternative take on this is that we are teaching people to become fluent that already know how to program! This means that it is already extremely likely that our students know how to create a file, and we are then forcing upon them a repetitive action that doesn't teach them anything new.

**Comment by sshine** [comment]
> I don't see why the C track is different from other tracks to be honest.

This.

I'm not a regular contributor to the Perl track, but we use it (and Exercism Teams) at work as part of training new hires, since most come without a Perl background. Some Perl track contributors prefer that there are no stubs for approximately the same reason that @wolf99 gives, and it is a valid reason. But I've witnessed how it affected our newcomers, and I don't think the gain is greater than the annoyance.

*(Sample bias: I've tried this with 5 hires, and they were all well-versed in one or more other languages, but they generally had problems figuring out what to put in the file, since there are no header files in Perl. Maybe the C track doesn't have that problem.)*

> My strong opinion is that the positives outway the negatives.

So the issue is not as much "It's more useful on track X" as it is "The maintainers of track X have autonomy to decide". The Exercism Project generally gives a *lot* of freedom to track maintainers, and I believe this is a strong motivator when you don't get paid.

So if you can't convince everyone that the positives outweigh the negatives, should there be a kind of voting of global policies and get done with it? Or in the case of being able to predict what the expected filename is, can we at least agree that even if the file is missing to begin with, a solution's files must be named predictably? Just like `"solution_pattern": "example.*[]hs"` occurs in `config.json`, we could have another key that guides the `exercism` CLI towards warning students that the proper file(s) were not submitted.

*(A side note on auto-mentoring and file prediction: The Haskell track hasn't got an auto-mentoring tool yet, but one problem that will eventually occur is that iterations that use external libraries are rarely accompanied by a `package.yaml` with the proper library inclusion. So I foresee that the problem extends to guiding the student towards submitting all the files that are technically necessary. Maybe others have found a similar problem and a way to deal with it.)*

**Comment by iHiD** [comment]
> The Exercism Project generally gives a lot of freedom to track maintainers, and I believe this is a strong motivator when you don't get paid.
> So if you can't convince everyone that the positives outweigh the negatives, should there be a kind of voting of global policies and get done with it?

If there's a question where there is no consensus (e.g the name vs description on problem-specifications right now, and seemingly this), and a decision needs making, then the leadership team will make a decision based on what everyone has said. However, as both Katrina and I have had a really busy couple of months that's not happened (as making a decision where lots of people disagree needs time and thought to get right) so there's a couple of issues like this that are lagging. 

With an issue like this, where I've specified a strong opinion up front and there is no overwhelming disagreement, it would probably, need a new "con" that I've not thought of in the introduction for me not to decide to move the policy forward.

**Comment by petertseng** [comment]
The summary of the below comment:

* I wanted to make a brief comment on the meta-issue of how decisions are made (maybe this is worth splitting off to its own discussion), so this comment will add no addition information regarding stubs
* It reads to me like leadership would prefer to exercise their authority as little as possible.
* I discuss situations where the benefits of a choice naturally encourage adoption without having to invoke authority, and some situations where we don't see that happen in this organisation.

Given the above observations that:

* it takes time and thought to make decisions on issues that lack consensus
* time and thought of the leadership team is finite by nature

I inferred that the leadership would prefer to only to invoke authority when necessary (of course, this is only an inference, worth what you paid for it).

One sort of situation where it is possible to minimise the burden on the leadership is when:

*  a certain choice has a natural benefit attached to it such as "If the track's maintainers make choice X, the maintainers' lives become concretely easier in Y way"
* AND the alternatives don't cause a worse experience for students and mentors.

In these situations, no consensus is necessary; maintainers that choose not to make choice X presumably have judged that they are willing to accept not having Y benefit, and no harm is done.

A common pattern in recent choices that lie outside the above category is: A choice made by maintainers may affect students and/or mentors. In these situations the natural alignment of incentives doesn't exist. Since maintainers are not necessarily students nor mentors, they aren't personally feeling the disadvantages of not making a certain choice. This is when the aforementioned wider knowledge comes in.

I don't know if it's possible to create more natural alignment of incentives, but if it were then more decisions would be easier. So I suppose the best I can do for now is to encourage looking for situations where it is possible to better align the incentives.

**Comment by iHiD** [comment]
Thanks @petertseng. That's helpful. I have one point to add clarity to. There are roughly two different areas of Exercism;

- **Open source side:** This includes tracks, problem-specs, analyzers, etc.
- **Product side:** Website, and the interactions around that with mentors/students etc.

(These are badly named, as both are open-source, and both are really about product, but hopefully the distinction is clear enough.)

We have a very firm grip on the product side (e.g. we don't generally accept PRs for the website, we say "this is the direction we're taking this feature" etc). That's because product work is best done by specialistic individuals or tightly formed teams, and also it often requires full-time effort. 

In contrast we aim to have a light touch on the "open source side". We are blessed with a variety of different people that maintain the majority of Exercism's code, and those variety of opinions tend to mean that everything self-regulates. In fact generally the maintainers know better than the leadership team what is actually needed. When people cannot self-regulate, what we really need is someone to say "Katrina, Jeremy - please can you make a decision on this", and then we'll do that.

This issue is slightly different, as I wrote it, with a firm opinion, asking for anything I might have not considered. It's also really a product question - "is this better/worse for students". The main reason I put it up for discussion rather than that as an announcement of something we're doing was that it impacts the maintainers' time as they will need to create stubs. 

I think the issue here is that I should have made a decision a while back and closed the issue, but I've had a very intense two months and got behind on things, so that didn't happen. I will rectify this in my next comment.

**Comment by iHiD** [comment]
So thank you all for your pitching in your thoughts 💙 

To conclude the discussion, I don't believe anyone has suggested anything new that wasn't in the OP. I agree that there is definite value in learning to create files, but I don't feel that that is something that Exercism should need to teach. The moment someone works on a project in the "real world" they'll learn how to create files if they don't know, and it won't be hard for them to work out. If we've tooled them up with everything but that skill, but made solving exercises less annoying for that person while learning, I'm fine with that situation.

So, I'm going to move forward with this proposal and ask all tracks to add stub-files to their exercises. When working through the Track Anatomy project, tracks can decide whether they want to provide content within those stubs, or just the empty files.

I'll work out with Katrina how best to communicate this to the everyone.

**Comment by gaitolini** [comment]
Suggestion to include stubs in Delphi track exercises

Hello, I would like to suggest that the Delphi track on Exercism include exercises with stubs, providing the minimal necessary structure (such as unit, class, class function, etc.).

Currently, the exercise files start completely blank, which can be extremely confusing for beginners. Additionally, many tests require the use of class function, and beginners might not be familiar with this syntax, increasing the difficulty unnecessarily.

I suggest that the exercise files provide the basic structure so that students can focus on the logic of the problem, instead of spending time setting up Delphi's structure. Here’s an example of what I mean:

delphi
`unit SumFunction;

interface

type
  TCalculator = class
  public
    class function Sum(a, b: Integer): Integer;
  end;

implementation

class function TCalculator.Sum(a, b: Integer): Integer;
begin
  // TODO: Implement the sum of the two values
end;`


end.
This would help:

Make life easier for beginners who are still learning Delphi’s syntax.
Reduce confusion, especially in exercises that involve class function and class var.
Improve consistency and reduce frustration for students who aren’t familiar with Delphi’s structural complexity.
Thank you!

**Comment by iHiD** [comment]
Hello. This is a 5 year old post. I suggest opening a new post on the forum (https://exercism.org/r/forum) with your suggestions. Thanks :)
