### ISSUE TITLE
Show comments of similar solutions

### ISSUE THREAD

**Issue by w1zeman1p** [exercism/discussions#38]
As a user, when I post a solution to an exercise that is nearly identical to someone else's, I want to see other solutions that are similar to mine and the comments associated with those, so that I can learn from what others have been taught and I don't have to rely on people constantly giving one on one feedback. 

1) On vimgolf i love that you can only see solutions that are just a little better than yours so you learn a little bit at a time
2) I find myself opening all the solutions for a few pages back of an exercise I just solved to read the comments on other solutions that were similar to see what critiques i could pick up without hoping that the best feedback would be spent on my solution
3) I've gotten some awesome feedback, shout out  to @remcopeereboom :) and it has resulted in some back and forth that might be valuable to others.

How might we do this? My first thought was to use some sort of static analysis tool to generate an AST from each solution and then run some sort of custom Levenshtein distance style algorithm to find which solutions are most similar. There might be enough solutions / trivial enough solutions that they could just use the actual Levenshtein distance :)

Another thought might be to give people a button that says: "hey that looks kinda like mine" to start to build a graph of similar solutions. 

This could probably also be solved in some UI way? maybe have two panes one on the left has your solution and then the right pane is a scrollable list of other folks solutions with comments?

**Comment by kytrinyx** [comment]
I think this would be incredibly valuable. I like the idea of using the AST rather than the actual code since that would remove some of the incidental differences.

> Another thought might be to give people a button that says: "hey that looks kinda like mine" to start to build a graph of similar solutions.

:) That hadn't occurred to me, but it might be the cheapest way to get started. I still like the AST + Levenshtein distance approach better. I wonder who might know enough about AIs and training them to do interesting things to think about other approaches to this.

**Comment by petertseng** [comment]
If we decide to take the automation approach, then we should combine the discussion with https://github.com/exercism/discussions/issues/65. though the crowdsourced approach is also getting a mention in https://github.com/exercism/discussions/issues/65#issuecomment-274340803

Basically I think we should merge these two discussions. I'll arbitrarily pick the other one since it's been around for longer, but feel free to overrule me.

**Comment by petertseng** [comment]
> been around for longer

Ha! an obvious lie, obviously 38 has been around longer than 65. I guess I should say I pick 65 because it's gotten more discussion, then?
