### ISSUE TITLE
Shall we get a bit more serious/strategic/systematic about using gitter?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#43]
Right now we've kind of tentatively started using gitter for support chat, and some people hang out there. Some individual language tracks have been creating gitter chat rooms (e.g. Ruby), where people can come ask questions about the ruby exercises specifically.

It seems like it might be useful to do this consistently across the board.

Things that worry me:
- who is going to monitor these conversations?
- who is going to moderate these conversations? What happens if someone joins and is consistently unpleasant?
- what happens if we have a room that is more or less inactive, and someone comes in and wants help? Will that disappointment affect their experience using Exercism in general?
- will people start using the rooms instead of having conversations on the site? If that's a concern, then what can we do to avoid it?

Things that we might do if we go forward with this.
1. stick a badge in each track repository README, linking to the correct room.
2. stick a link to the gitter room in the $TRACK/SETUP.md, which would include it in each exercise README (perhaps with verbiage about trying that if they get stuck, perhaps also with something about how the rooms might not be active, in which case... what would we recommend that they do?)
3. include it in the documentation about the language on exercism.io/languages/:track_id
4. include it in the code/solution/submissions page on the exercism.io website (or maybe not, because this might encourage people to use it instead of commenting on the site)

**Comment by LegalizeAdulthood** [comment]
I like the idea of this, but I don't have cycles to be a hall monitor :smiley_cat:

**Comment by LegalizeAdulthood** [comment]
Just another thought: Is slack a better alternative to gitter?

**Comment by mhelmetag** [comment]
I'll put in a vote to not use Slack for a few reasons: another login (gitter uses github), managing invites (you need to invite people to slack organizations (in gitter, people can just join on their own accord), not as scalable as gitter (freecodecamp uses gitter and it works well).

I check the gitter group fairly often. I think that having help and pairing channels could be really cool.

**Comment by LegalizeAdulthood** [comment]
The single login is good enough reason, I hadn't thought of that and I agree.  After I posted that question I googled slack vs. gitter and came upon the post by the freecodecamp folks describing their experience.  I don't know what the size of the exercism user base is, but their experience gives me a reason to prefer gitter.

**Comment by mhelmetag** [comment]
We could have a chatbot that has admin privileges that users can interface with to create votes to ban users/block content.

Freecodecamp has https://github.com/FreeCodeCamp/camperbot (he's more of a kudos bot than a robocop though; I do like the idea of a robocop chatbot 💡 ).

> will people start using the rooms instead of having conversations on the site? If that's a concern, then what can we do to avoid it?

I think that one option would be to not have chat rooms for each language where users go to get help. I believe that is what comments on the site are for. I think that the chat would be helpful for talking about other things like promoting cool languages, sharing ideas and resources, etc. Just to get a more active community going.

**Comment by LegalizeAdulthood** [comment]
I like the idea of one gitter chatroom for all of exercism and not fracturing the participants into balkanized communities by languages.

**Comment by kytrinyx** [comment]
> I think that the chat would be helpful for talking about other things like promoting cool languages, sharing ideas and resources, etc. Just to get a more active community going.

Yes! And helping people who get stuck when installing the client :)

Agreed, though, that fracturing the participants into communities by language is probably not a good idea.

**Comment by kotp** [comment]
The fracturing by language happens naturally by the fact that there are separate tracks.  But I don't think that is terrible.  You isolate the focus, but are free to join more than one community, er, language.

"balkanized" as a description, may be a bit harsh, I don't think it was ever intended to break up into smaller, often hostile, groups... just themed topic areas.  And I don't think I have seen the balkanization happen, only friendly conversations, and inclusion.

I had not hoped to fracture the community, only the topics.  (I had introduced the Ruby room.)

The rooms are not busy enough to lose a topic though, so having one would probably still work very well.  But, with that said, I don't think conversations about exercism internals and exercism exercises would be very coherent mixed together.

Other than the language rooms, the common rooms seem to be dev and support.  So far, dev seems to be mostly infrastructure conversations and support seems to be (less) infrastructure and (more) user support.  This could be further demarcated.

Any discussion about exercises in particular, hasn't seemed to happen that I have seen in the individual rooms... but discussions in tracks have made it out to gitter and issues on github.  So that is good.

As far as 'getting help' the rooms work well for that, but with the "help flags" coming, I think that will really help on the exercism site.

**Comment by kytrinyx** [comment]
> I don't think conversations about exercism internals and exercism exercises would be very coherent mixed together

This is a good point.

I think there are probably four types of conversations that happen in the chat (correct me if I'm wrong)

- help getting started (installing the CLI, confusing website, etc)
- discussion about exercism features/internals/development
- help with a specific language
- friendly chatter

Most of that is totally fine in the general support channel or the dev channel, but since most people don't know most languages (there are exceptions!) a lot of people asking for help might not get it. For languages where there's a lot of activity, it might clutter up the general support channel.

**Comment by kotp** [comment]
The "I asked in (some busy) the channel, and never got an answer" is what I would like to avoid.  I think you are categorizing the conversations properly.

I also do monitor (I think all of) the rooms, even if I am not good with the language.  Just because if someone needs help, I know where to go to find someone that can, or direct them to the right place, if it is more of an issue that can or should be addressed on github issues.

**Comment by kytrinyx** [comment]
> The "I asked in (some busy) the channel, and never got an answer" is what I would like to avoid.

Yeah, that's definitely something to avoid.

> I also do monitor (I think all of) the rooms, even if I am not good with the language.

:heart: :heart: :heart:

I'm OK with leaving this as it is now (somewhat ad-hoc), and we can revisit later when we've had more experience with it.

**Comment by kytrinyx** [comment]
The conclusion a year ago was to leave "as is" for now. Closing.

**Comment by kotp** [comment]
I have recently again received a request for a gitter exercism/cpp room.  I  do not have the access to create it properly.  @iHiD or @ErikSchierboom ??

And those gitter rooms are monitored by myself and a few others, along with the IRC chat room.

**Comment by iHiD** [comment]
Is there enough activity there to warrant a separate room, rather than just using support? For mentoring/maintaining conversations, I'd rather they were on Slack.

**Comment by kotp** [comment]
Do students get invited to slack?  That would be the thing.  I would let the students self-energize the rooms on Gitter for their languages.  And while `dev` is there as a room, the support room is what this student is, I think, indicating is not appropriate for general cpp student discussions.

**Comment by kotp** [comment]
I mean, it does not matter to me, I monitor all the rooms that we have.  I just can not create them for the organization.

**Comment by iHiD** [comment]
I've added it.

**Comment by kotp** [comment]
Thank you, I have let them know.
