### ISSUE TITLE
Submit an exercise with a help flag

### ISSUE THREAD

**Issue by raydancer** [exercism/discussions#47]
I'm currently stuck on a JavaScript exercise and I'm not really sure how to get help.  I'd really like to see an option to submit unfinished code with a very visible help flag (I cobbled together an icon).  I'd also like to sort exercises to see who needs help.  Being a newb, I'm pretty limited on any capability of implementing these things; I know a moderate amount of JavaScript, and a tiny bit of Ruby, but I've never really used Git or Github until now.  What should I do from here?

![help_flag](https://cloud.githubusercontent.com/assets/6845482/16541708/addee92c-4058-11e6-9f5c-e05ab0d59e6f.png)

**Comment by IanWhitney** [comment]
An almost-totally-unknown aspect of Exercism is that you can submit code that doesn't work. Then you can look at other people's solutions. I think it would be great if we could document this and make it part of the problem readmes.

Another almost-totally-unknown method is to look at the example solution. If, for example, you were stuck on the Acronym problem in Javascript, you could look at its [example solution](https://github.com/exercism/xjavascript/blob/master/exercises/acronym/example.js).

These example solutions aren't publicized because the originally existed only to make sure that tests were accurate. But in [a recent discussion](https://github.com/exercism/discussions/issues/27) we talked about making them more `exemplary`, which would make them useful for stuck students. So maybe we could have a problem's readme point towards the example.

**Comment by raydancer** [comment]
I knew that I could submit unfinished code, but didn't consider that it would allow me to view other submissions.  When viewing other user submissions, is it possible to tell whether their code passes the spec without running the tests on it yourself?

I had no idea that there were example solutions.  That is very helpful, and I definitely think that should be mentioned somewhere.

All that said, I still think it would be nice to add a help flag to a submission.  Currently, the only way to know if someone has a question is to look at the comments on every submission.

**Comment by kytrinyx** [comment]
> When viewing other user submissions, is it possible to tell whether their code passes the spec without running the tests on it yourself?

No, not directly. We have the `exercism download $UUID` command to make it easier to download and run their code, though (you'd have to unskip the tests, which makes it a bit cumbersome). You get the UUID from the URL when looking at their solution.

I would hope that if people didn't get it running, they would say something about it in the conversation that goes with it.

> All that said, I still think it would be nice to add a help flag to a submission. Currently, the only way to know if someone has a question is to look at the comments on every submission.

Yeah, this would be really useful. We could flag these especially in the stream.

**Comment by ramyaravindranath** [comment]
@kytrinyx : I am looking into the issue. How about adding a new boolean attribute/column "help" to submission table ? And have a help flag on active stream on exercism.io. User can flag the help option if any help needed on the submission.

**Comment by kytrinyx** [comment]
@ramyaravindranath Thank you. Since the activity streams list exercises (rather than submissions), I think it would make more sense to have a separate table for help requests. Hm. Actually, a boolean on `user_exercises` would probably make more sense. We're never going to have more than one help flag at a time.

**Comment by ramyaravindranath** [comment]
https://github.com/exercism/exercism.io/pull/2995

**Comment by petertseng** [comment]
Given we have https://github.com/exercism/discussions/issues/54 and https://github.com/exercism/exercism.io/pull/2995 I would say we have addressed the need of:

>  I'd really like to see an option to submit unfinished code with a very visible help flag

There is an interesting possible additional issue, though it is a separate discussion altogether:

> is it possible to tell whether their code passes the spec without running the tests on it yourself?
