### ISSUE TITLE
What is this repo for?

### ISSUE THREAD

**Issue by patricksjackson** [exercism/discussions#48]
I am new to Exercism, so I've been trying to wrap my head around how things are organized. Maybe I'm missing something, but I can't even find a description of what all the repos are used for.

(It looks like this documentation has sort of begun with https://github.com/exercism/exercism.io/issues/2924, but that doesn't even mention this repo or x-common)

_If this extra discussions repo is going to be useful, there need to be very clear lines on what goes in here, in exercism.io, and in x-common. And crucially, **it needs to be documented and enforced.**_

This repo seems to be setup for high-level discussions for the exercism project as a whole. Since I'm new here I'll refrain from trying to define what 'high-level discussions' actually means, but I will make one suggestion:

For a project with 76 (!) repos you have to have a centralized place for documenting the across project conventions and best practices. That's the only way you'll be able to track the whole project status (with consistent issue labels), easily onboard newcomers who want to do more than just contribute to a single track, and it'll also let you easily tell if a track maintainer has dropped off. 

I suggest that the documentation of best practices stays in the same repo as the high-level discussions, as any discussion about that documentation is a high-level discussion by definition. That would just mean centralizing your project documentation here, so you can have one entry point into contributing.

**Comment by kytrinyx** [comment]
Thanks for your feedback, @patricksjackson!

> I've been trying to wrap my head around how things are organized.

Yeah, everything has been pretty chaotic, and we're only starting to figure out how to organize this. I've been working on trying to figure out how to overhaul all of the documentation to make it easier to get around, even in the chaos. Over time, I hope that we will be able to also get the code into a more understandable state.

> there need to be very clear lines on what goes in here, in exercism.io, and in x-common.

Yes, I absolutely agree. We're trying to figure this out. My goal is to have every single issue where the action item is 'discuss', or 'figure out' or 'decide' in this repository. All issues in any other repository would ideally be an issue that one could do something specific to solve. This still isn't clear enough, and there is some work to do with triage in order to discover the nuances involved.

> I suggest that the documentation of best practices stays in the same repo as the high-level discussions

That's a good suggestion, thanks.

**Comment by kytrinyx** [comment]
I've opened the above issue about philosophy about which repository to open issues in so that we can get some consensus and then document it. Thanks for kicking off this discussion, @patricksjackson!
