### ISSUE TITLE
Can I download many solutions to a particular problem easily?

### ISSUE THREAD

**Issue by lbain** [exercism/discussions#51]
### Background (feel free to skip)

I'm doing a [study group](http://www.meetup.com/Sydney-programming-study-group/events/231933324/) for Udacity's software debugging course. I wanted to find smallish slightly buggy code that we could work on debugging for our meetings. Since I use Exercism and love how well the tests are done I figured it would be a good place to find some solutions that don't pass all the tests and try to finish them off.

I [asked](https://twitter.com/lucykbain/status/749907473528606724) if it was possible to download a bunch of solutions for any given problem (from there I would run the tests locally and find which are passing or failing). The answer was that I could, but I needed the _solution's_ UUID. However, when you look at the source for the Inbox page the links are to /exercises/UUID, not /solutions/UUID.
### Problem

The command `exercism download` requires the solution UUID, which isn't easily available on the site. (Please correct me if I'm wrong about this.)
#### Icky solution

I ended up writing a little script that would pull down the bits I needed. But it has to make two requests for each solution (one to convert from the exercise's UUID and another to get the solution's code) so I feel a bit bad about doing that. My code is below for future users (or feedback - bash isn't something I write in frequently...)

```
# get a list of the exercises' UUIDs by running this line in the console on the inbox page:
# $('a.exercise').map(function() { return $(this).attr('href').split('/')[2] });
declare -a exercise_urls=(UUIDS_HERE)

for i in "${exercise_urls[@]}"
do
  submission_url=$(curl "http://exercism.io/exercises/$i" -s -L -I -o /dev/null -w '%{url_effective}')
  submission_uuid=`basename $submission_url`
  exercism download $submission_uuid >/dev/null
done
```

This isn't a big deal - I understand I'm in a very edge case situation.

**Comment by kytrinyx** [comment]
This is such a good question, and I would love to get this working. I currently do a completely dirty thing which (sob!) only I can do, because I have access to the production data. I would much, much prefer to have a generic solution to this.

I actually think it would be awesome if we could have this to make it easier to explore existing solutions, which I think a lot of people would learn from.

Also, I really think that we should start considering submitting the test file by default (submitting everything), so that when people restore, we have the tests that _they_ ran against, not the current test suite (to make things worse: with things pending/skipped, if the language track does that).

Possibly related: https://github.com/exercism/discussions/issues/35

Bringing in @exercism/cli-committers on this.

**Comment by kytrinyx** [comment]
It's been over a year, and I imagine that you've likely moved on in your research.

We've spent the past 9 months doing some very intense product work to figure out what Exercism is and isn't, as the basis for a redesign (see https://github.com/exercism/v2-feedback/blob/master/README.md).

As part of this, it's become very clear what Exercism's primary purpose is (helping people become fluent in a language).

While we dearly love science we won't be optimizing for this use case. We may find ways of making this possible in the future, but at the moment we don't have the bandwidth to work on it.

I'm going to go ahead and close this, but as the new site takes form and we start having more bandwidth, I'd be willing to consider ways of making something like this possible.
