### ISSUE TITLE
Problems - how can we guide newbies through languages?

### ISSUE THREAD

**Issue by gusseting** [exercism/discussions#52]
@ramyaravindranath and I are working on exercism as part of Rails Girls Summer Of Code.
Here's what we've found:
What we've learnt about how people use exercism, and what the problem is - they're looking for a synopsis of what they're going to learn, and that's not how exercism works.

We've had the same issue with trying to categorize exercism problems in that we can't, because that's not how exercism, or the problems in that particular language (eg Ruby) works.

So...does there need to be a change and more guidance to newbies so that they have a guide in how they might solve a problem?
eg: here’s one way to solve the problem…., and info re: what they'll learn with those guides?

Would it assist newbies to have a newbie track to problems?

The issue of guiding newbies/providing guidelines of how to solve problems is also discussed in  https://github.com/exercism/discussions/issues/44

**Comment by kytrinyx** [comment]
> they're looking for a synopsis of what they're going to learn, and that's not how exercism works.

Would you say more about this? Do you mean that they've misunderstood what Exercism is, or that Exercism is currently missing something that tells them what they'll learn?

We could talk about fluency vs proficiency as per languagehunters.org.

Fluency: _What you can say in the middle of the night when someone wakes you up with a flashlight in your face._

You can be fluent at a low level of proficiency. What Exercism seeks to do for people who are learning to program or learning a new language, is to give people enough exercises that are fairly trivial (no real-world domains, no real-world codebase sizes), which will give them an opportunity to become fluent at the basic syntax of the language.

For people who are new to programming, it will also teach them a lot about how to break problems down into smaller steps when solving them, and a bit about automated testing of code.

They'll also gain familiarity with the conventions and idioms in the language... meaning that they will look and sound like a "native speaker", even though they might be solving trivial/toy problems rather than having the code equivalent of social/political/economic conversations.

Does that make sense?

> We've had the same issue with trying to categorize exercism problems in that we can't, because that's not how exercism, or the problems in that particular language (eg Ruby) works.

We should be able to categorize problems to some extent. See https://github.com/exercism/x-common/issues/63 and https://github.com/exercism/x-common/issues/71

> So...does there need to be a change and more guidance to newbies so that they have a guide in how they might solve a problem?

Yeah, maybe. There's a lot of guidance in the ruby hello-world exercise. Is this the kind of guidance you were thinking about?

> eg: here’s one way to solve the problem…., and info re: what they'll learn with those guides?

I'm not sure I understand what this means. Would you elaborate?

> Would it assist newbies to have a newbie track to problems?

Again, I'm not sure what this means. Would you elaborate?

**Comment by kytrinyx** [comment]
I'm going to close this in favor of https://github.com/exercism/discussions/issues/31
