### ISSUE TITLE
Detecting potentially abandoned pull requests

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#56]
I saw a great comment from @Insti today: https://github.com/exercism/xruby/pull/342#issuecomment-234741907

I've been pondering the need for some more structure around people calling "dips" and then not following up, or submitting a pull request, getting requests for fixes, and then not following up.

Should we have some sort of default time limit where if we don't hear back, we ask a question (this could be a bot) and then if nobody comments after the bot comments, the bot could automatically close this a week later (or something)?

I'm sure there are already existing bots that do this sort of thing, so we might be able to base this on existing tools.

I guess my questions are:
- Is this something we want to do?
- If so, what are the time limits?
- And also: does anyone know of good bots that we could work off of?

/cc @exercism/track-maintainers because this affects everyone.

**Comment by scottwhudson** [comment]
As a new contributor, I would find something like this helpful.  Currently, it takes a lot of time to read through issues in each repo to find something to work on that isn't claimed. And then if the activity on this issue is dead, I have to ask users in the thread if this is active or needs reassignment, and responses can take a few days, etc. etc.  The whole process can take days, and I think we can all agree it's more fun to commit code than it is to find things to do. :) 

In exercism's case, we could schedule a basic daily task using the Github API that monitors each repo and comments on issues as needed.  I'm thinking something like this:

1. fetch all assigned issues on a repo and iterate through each issue
1. find the date of the last comment or branch ref by the assignee and subtract it against the current date to determine if the waiting period has expired
1. if the specified waiting period has expired:
 *  post comment alerting the assignee saying they have 24 hours|days|whatever to comment on the issue to restart the waiting period, or ignore the comment and allow the task to remove the assignment and move the issue back to an available state
1. On the next day|week|whatever and if the user hasn't responded, post an automated "this issue is back up for grabs" comment on the thread and remove the issue assignment

Not that I'm against bots by any means, that just seems like more code to introduce than needed to solve this particular problem.

**Comment by kytrinyx** [comment]
> The whole process can take days, and I think we can all agree it's more fun to commit code than it is to find things to do.

Agreed! I've been thinking about triage a lot in the past few weeks—the current state of the issues is a huge barrier to contributing.

You're right—we don't need a whole bot for this. I think your script approach sounds great. I figure we can set this up to run on a cron job on our rackspace server (or something). Or even as a scheduled job in Exercism on Heroku.

>  ref by the assignee 

We can't use assignee directly, unfortunately, because GitHub only allows assigning team members, so we basically don't use that.

We could add a specific label to issues that are taken, and then maybe a comment that has a specific format to say who is fake-assigned. That way we can fetch only issues with the relevant label, and parse through the comments backwards to figure out who has called dibs. Or something :)

@Insti @kotp do you have any thoughts on how to tackle this?

**Comment by avisrivastava254084** [comment]
So? Anything mentioned been implemented?

**Comment by kotp** [comment]
Not that I am aware of.  And it is the "silence" that ends up being missed... we do need a little noise maker when things (like this one) get quiet.

I have been using Zenhub to mark things on my "Todo" list, which is helping to keep things visible and checked.  But having a :bell: that gets our attention in some way would be a good thing.

**Comment by mhelmetag** [comment]
Having some super simple version of [bors](https://github.com/graydon/bors) would be interesting. Just a small worker that looks at open pull requests (for the exercism repos) daily and comments a little bell on them or poke message if nothing has happened in a few weeks. Seems like fun.

**Comment by Insti** [comment]
This discussion seems to have been resolved in https://github.com/exercism/discussions/issues/128

Where [Probot](https://github.com/integration/probot-stale) has been chosen for the task of prompting/closing old issues.

**Comment by Insti** [comment]
Unless it only handles issues and not pull requests?

**Comment by kytrinyx** [comment]
No, it doesn't limit itself to just issues: https://github.com/exercism/exercism.io/blob/master/.github/stale.yml#L21
