### ISSUE TITLE
`exercism fetch <lang> --next`

### ISSUE THREAD

**Issue by ashleygwilliams** [exercism/discussions#72]
apologizes if a feature like this has already been discussed. i only saw an issue for a "Next" button on the website. but similarly, i'd like to be able to fetch the next exercise from my terminal without having to look up the name
### behavior
- from `exercism/<lang>` directory, type `exercism fetch <lang> --next`
- based on present exercise directories, fetch the exercise that comes directly after the exercise that is the most advanced
### example

```
$ pwd
~/exercism/rust/
$ ls
gigasecond hello-world
$ exorcism fetch rust --next

Not Submitted: 1 problem
rust (Leap) /Users/ag_dubs/exercism/rust/leap

New:        1 problem
rust (Leap) /Users/ag_dubs/exercism/rust/leap

unchanged: 0, updated: 0, new: 1
```
### requirements
- i'm not sure if the exercises have an order as part of the data structure, or if not all language exercises are ordered. i would think they would be, at least at the beginning, though i can also imagine as they get more advanced, order matters less. having an order would be key to implement this.
- probably would need to reserve the next word, i.e. no exercise could be called next

**Comment by petertseng** [comment]
> i'm not sure if the exercises have an order as part of the data structure, or if not all language exercises are ordered

It is a certainty that all languages' exercises are ordered. The order is defined in the config.json file for each track. For example, https://github.com/exercism/xrust/blob/master/config.json - the order in the `exercises` array is the in which the exercises will be fetched.

> from `exercism/<lang>` directory,

In fact, I think this can be loosened; it doesn't have to be done from that directory.

> fetch the exercise that comes directly after the exercise that is the most advanced

I was about to suggest the already-implemented `exercism fetch <lang>` without an exercise argument, but I noticed in that your requested behavior it differs from `exercism fetch <lang>`. I believe `fetch` without an exercise slug fetches the earliest unsolved exercise (I believe!), instead of the exercise immediately following the latest solved exercise.

Let's say that the exercises for `<lang>` are ordered 1, 2, 3, 4, 5, and the student has solved 1 and 3. `exercism fetch <lang>` would fetch 2, whereas the requested `--next` would fetch 4.

However `exercism skip` is also available for those students who don't ever want to fetch 2. So `--next` still may not be necessary.

Does there remain a case where `skip` and `fetch` without exercise slug do not cover the desired behavior?

**Comment by kytrinyx** [comment]
> I believe fetch without an exercise slug fetches the earliest unsolved exercise (I believe!), instead of the exercise immediately following the latest solved exercise.

Yes, that is correct, and `exercism skip TRACK_ID SLUG` is the way to work around it.

**Comment by Cohen-Carlisle** [comment]
One advantage I can see to adding `exercism fetch --next` is that people have to know about `fetch` to use exercism but they may not know about `skip`. I must admit I'm not even 100% sure what `skip` does and have never used it, but `exercism fetch --next` seems simple and easy to understand.

**Comment by kytrinyx** [comment]
@Cohen-Carlisle that's a good argument. Also, we could deprecate `skip` in favor of `fetch --next` which would feel cleaner.

**Comment by Tonkpils** [comment]
I like the idea of deprecating `skip` in favor of adding something that feels more streamlined, in this case with the `fetch` command. 

When I first read the comments on the issue I thought `next` sounded a bit confusing. However, as long as we explain `fetch` behavior with and without the `--next` flag I think it'll be ok.

**Comment by kotp** [comment]
I prefer the flag as well.

**Comment by kytrinyx** [comment]
I've added this to the discussion about the CLI redesign ^^ - closing in favor of the broader discussion. Thanks @ashleygwilliams!
