### ISSUE TITLE
Go: What is food-chain trying to teach?

### ISSUE THREAD

**Issue by crmejia** [exercism/discussions#75]
Hi,

I'm new here and not sure where to ask this. I apologize if this is not the place to ask(can you point me in the right direction?)

Anyway, I just finished food-chain using Go. I spent  2-3hrs trying to get just right. This exercise got me wondering what it taught me. I did ask in the [exercise.](http://exercism.io/submissions/cfa68091e6594ed889161f8ffb597a8f) However, I started thinking about the bigger picture, maybe it would be good if the exercise had a brief description or hints after is finished of what concepts we should consider. Does this sound like a good idea or am i missing something?

**Comment by jtigger** [comment]
I think this is a legitimate goal: seeking to understand why.

I wonder if this can be discovered by exploring how others approached the same problem.  Sometimes, seeing the same problem solved in different ways can illuminate what's common (and likely what's "interesting" or "worthwhile" about an exercise.

To be more direct, these kinds of exercises invoke general design challenges.  It's very common to hatch expedient abstractions instead of those that reveal the concepts inherent in the domain.

Sounds like the experience was a bit frustrating.

**Comment by crmejia** [comment]
I agree with your 2nd paragraph. I've checked other solutions every time I completed an exercise. I do learn if my approach was common, other approaches, and sometimes clever tricks. For this exercise, I saw similar answers: a struct or a map, a for loop to generate verses, and Sprintf.
 
Yes the experience was a bit frustrating. I spent more time than usual on the problem.

**Comment by jtigger** [comment]
@exercism/golang, thoughts?

**Comment by kytrinyx** [comment]
The food-chain exercise is about refactoring, to my mind. I did a talk about how I approached the refactoring exercise in Ruby here: http://www.kytrinyx.com/talks/succession/

In Go the code would end up being very different of course.

> maybe it would be good if the exercise had a brief description or hints after is finished of what concepts we should consider.

It could be. We're working on adding topics to the language track configuration for each exercise, and it might be worth exposing that to people https://github.com/exercism/discussions/issues/60
